In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('sprint_2_responses.xlsx')
df.set_index('Selecione o seu Nome', inplace=True)
df.drop(['Timestamp'], axis=1, inplace=True)

In [3]:
columns = df.columns

In [4]:
new_columns = {}
for column in columns:
    # posição das palavras 'PRODUTIVIDADE', 'PROATIVIDADE', 'TRANSPARÊNCIA' no nome da coluna
    categoria = column.split()[3]
    nome = column.split('[')[-1].replace(']','')
    #removendo texto desnecessário da coluna e renomeando no padrão ex: PRODUTIVIDADE - NOME DO ALUN@
    new_columns[column] = f'{categoria} - {nome}'

In [5]:
df.rename(columns=new_columns, inplace=True)

In [6]:
responder = []

In [7]:
transposed = df.T
for aluno in df.index:

    index_filter = [index for index in transposed.index if 'PRODUTIVIDADE' in index]
    if 5 in list(transposed.loc[index_filter, aluno].dropna()):
        responder.append(aluno)

In [8]:
responder

[]

In [67]:
#respostas do aluno
aluno = 'ARTHUR MARTINS DE SOUZA BARRETO'
transposed.loc[index_filter, aluno].dropna()

PRODUTIVIDADE - ANTÔNIO AMARAL EGYDIO MARTINS      4.0
PRODUTIVIDADE - ARTHUR MARTINS DE SOUZA BARRETO    4.0
PRODUTIVIDADE - ARIEL TAMEZGUI LEVENTHAL           4.0
PRODUTIVIDADE - MURILO PRADO WEYNE                 4.0
Name: ARTHUR MARTINS DE SOUZA BARRETO, dtype: float64

In [71]:
#respostas do aluno
aluno = 'ARTHUR MARTINS DE SOUZA BARRETO'
index_aluno = [linha for linha in transposed.index if aluno in linha] 

transposed.loc[index_aluno,:]

Selecione o seu Nome,ANDRÉ BRITO,ANDRÉ CORRÊA SANTOS,ANTÔNIO AMARAL EGYDIO MARTINS,ARIEL TAMEZGUI LEVENTHAL,ARTHUR BOSCHINI DA FONSECA,ARTHUR CISOTTO MACHADO,ARTHUR MARTINS DE SOUZA BARRETO,CAIO DE CAMARGO ARANHA TIERI,CAIO TRAVAIN,DOM RUAN SUZANO FIGUEIRA DA SILVA,...,MURILO PRADO WEYNE,PEDRO BITTAR BARÃO,PEDRO CLIQUET DO AMARAL,PEDRO PAULO MORENO CAMARGO,RAFAEL COCA LEVENTHAL,RAFAEL MELHADO ARAUJO LIMA,RODRIGO ANCIÃES PATELLI,THOMAS CHABRO,VICTOR LUIS GAMA DE ASSIS,VINICIUS MATHEUS MORALES
PRODUTIVIDADE - ARTHUR MARTINS DE SOUZA BARRETO,NaN,NaN,3.0,4.0,NaN,NaN,4.0,NaN,NaN,NaN,...,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PROATIVIDADE - ARTHUR MARTINS DE SOUZA BARRETO,NaN,NaN,4.0,4.0,NaN,NaN,4.0,NaN,NaN,NaN,...,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TRANSPARÊNCIA - ARTHUR MARTINS DE SOUZA BARRETO,NaN,NaN,3.0,3.0,NaN,NaN,4.0,NaN,NaN,NaN,...,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [75]:
index_aluno
df.loc[:,index_aluno].dropna()

,PRODUTIVIDADE - ARTHUR MARTINS DE SOUZA BARRETO,PROATIVIDADE - ARTHUR MARTINS DE SOUZA BARRETO,TRANSPARÊNCIA - ARTHUR MARTINS DE SOUZA BARRETO
Selecione o seu Nome,,,
ANTÔNIO AMARAL EGYDIO MARTINS,3.0,4.0,3.0
ARIEL TAMEZGUI LEVENTHAL,4.0,4.0,3.0
ARTHUR MARTINS DE SOUZA BARRETO,4.0,4.0,4.0
MURILO PRADO WEYNE,2.0,2.0,2.0

In [42]:
#Exemplo: pegando resposta com valor 5 em PRODUTIVIDADE
aluno = 'ANDRÉ BRITO'
5 in list(transposed.loc[index_filter, aluno].dropna())

True