In [1]:
import pandas as pd

In [3]:
df = pd.read_excel('sprint_2_responses.xlsx')

In [4]:
df.set_index('Selecione o seu Nome', inplace=True)
df.drop(['Timestamp'], axis=1, inplace=True)

In [5]:
columns = df.columns

In [6]:
df

,"Qual nível de PRODUTIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [ANDRÉ CORRÊA SANTOS]","Qual nível de PRODUTIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [PEDRO PAULO MORENO CAMARGO]","Qual nível de PRODUTIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [RAFAEL MELHADO ARAUJO LIMA]","Qual nível de PRODUTIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [ANDRÉ BARBOZA BRAGA DE MELO]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [ANDRÉ CORRÊA SANTOS]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [PEDRO PAULO MORENO CAMARGO]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [RAFAEL MELHADO ARAUJO LIMA]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [ANDRÉ BARBOZA BRAGA DE MELO]","Qual nível de TRANSPARÊNCIA cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [ANDRÉ CORRÊA SANTOS]","Qual nível de TRANSPARÊNCIA cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [PEDRO PAULO MORENO CAMARGO]",...,"Qual nível de PRODUTIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [CAIO DE CAMARGO ARANHA TIERI]","Qual nível de PRODUTIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [FELIPE TRINTIM]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [THOMAS CHABRO]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [RAFAEL COCA LEVENTHAL]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [CAIO DE CAMARGO ARANHA TIERI]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [FELIPE TRINTIM]","Qual nível de TRANSPARÊNCIA cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [THOMAS CHABRO]","Qual nível de TRANSPARÊNCIA cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [RAFAEL COCA LEVENTHAL]","Qual nível de TRANSPARÊNCIA cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [CAIO DE CAMARGO ARANHA TIERI]","Qual nível de TRANSPARÊNCIA cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [FELIPE TRINTIM]"
Selecione o seu Nome,,,,,,,,,,,,,,,,,,,,,
FERNANDO GIUSEPPE AVILA BELTRAMO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ERIC ANDREI LIMA POSSATO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
GUILHERME DOS SANTOS MARTINS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PEDRO PAULO MORENO CAMARGO,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ANDRÉ CORRÊA SANTOS,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ANTÔNIO AMARAL EGYDIO MARTINS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
GIOVANA CASSONI ANDRADE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ENZO BOZELLI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
RODRIGO ANCIÃES PATELLI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
VINICIUS MATHEUS MORALES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
VICTOR LUIS GAMA DE ASSIS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ARTHUR MARTINS DE SOUZA BARRETO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LUCAS GURGEL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LINCOLN RODRIGO PEREIRA MELO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DOM RUAN SUZANO FIGUEIRA DA SILVA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
HUDSON MONTEIRO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
JOÃO GABRIEL VALENTIM ROCHA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MURILO PRADO WEYNE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CAIO RIBEIRO DE PAULA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ARIEL TAMEZGUI LEVENTHAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PEDRO CLIQUET DO AMARAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ANDRÉ BRITO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ARTHUR CISOTTO MACHADO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MARLON SILVA PEREIRA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
RAFAEL ELI KATRI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PEDRO BITTAR BARÃO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FERNANDA DE OLIVEIRA PEREIRA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LEONARDO DA FRANÇA MOURA DE ANDRADE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
RAFAEL COCA LEVENTHAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0

In [7]:
new_columns = {}
for column in columns:
    # posição das palavras 'PRODUTIVIDADE', 'PROATIVIDADE', 'TRANSPARÊNCIA' no nome da coluna
    categoria = column.split()[3]
    nome = column.split('[')[-1].replace(']','')
    #removendo texto desnecessário da coluna e renomeando no padrão ex: PRODUTIVIDADE - NOME DO ALUN@
    new_columns[column] = f'{categoria} - {nome}'

In [8]:
df.rename(columns=new_columns, inplace=True)

In [9]:
alunos = list(df.index)
#Dicionário para armazenar as médias para criar um novo dataframe
data = {
    'nome':[],
    'media_produtividade':[],
    'media_proatividade':[],
    'media_transparência':[],
    'auto_produtividade':[],
    'auto_proatividade':[],
    'auto_transparência':[],
    'media':[]
}

In [10]:
categorias = ['PRODUTIVIDADE', 'PROATIVIDADE', 'TRANSPARÊNCIA']
for aluno in alunos:
    data['nome'].append(aluno)
    soma = 0
    for categoria in categorias:
        nome_coluna = f'{categoria} - {aluno}'
        media_colegas = df.loc[(df.index != aluno) ,nome_coluna].dropna().mean()
        soma += media_colegas
        
        auto_avaliacao = df.loc[(df.index == aluno) ,nome_coluna][0]
        
        data[f'media_{categoria.lower()}'].append(media_colegas)
        data[f'auto_{categoria.lower()}'].append(auto_avaliacao)
    data['media'].append(soma/3)

In [ ]:
# data

In [11]:
df_medias = pd.DataFrame(data=data)

In [12]:
df_medias['dif_produtividade'] = df_medias['media_produtividade'] - df_medias['auto_produtividade']
df_medias['dif_proatividade'] = df_medias['media_proatividade'] - df_medias['auto_proatividade']
df_medias['dif_transparência'] = df_medias['media_transparência'] - df_medias['auto_transparência']

In [13]:
df_medias.loc[:,['nome','dif_produtividade','dif_proatividade','dif_transparência']]

,nome,dif_produtividade,dif_proatividade,dif_transparência
0,FERNANDO GIUSEPPE AVILA BELTRAMO,0.000000,0.000000,0.000000
1,ERIC ANDREI LIMA POSSATO,0.000000,0.000000,0.000000
2,GUILHERME DOS SANTOS MARTINS,0.000000,0.333333,0.333333
3,PEDRO PAULO MORENO CAMARGO,0.000000,0.000000,0.000000
4,ANDRÉ CORRÊA SANTOS,0.000000,0.000000,0.000000
5,ANTÔNIO AMARAL EGYDIO MARTINS,0.666667,-0.333333,0.666667
6,GIOVANA CASSONI ANDRADE,0.000000,0.333333,0.333333
7,ENZO BOZELLI,0.500000,0.500000,0.500000
8,RODRIGO ANCIÃES PATELLI,0.500000,0.000000,0.500000
9,VINICIUS MATHEUS MORALES,0.000000,0.000000,0.000000
10,VICTOR LUIS GAMA DE ASSIS,-0.666667,-0.666667,-0.333333
11,ARTHUR MARTINS DE SOUZA BARRETO,-1.000000,-0.666667,-1.000000
12,LUCAS GURGEL,0.666667,0.666667,1.000000
13,LINCOLN RODRIGO PEREIRA MELO,0.500000,0.000000,0.000000
14,DOM RUAN SUZANO FIGUEIRA DA SILVA,0.000000,0.000000,0.000000
15,HUDSON MONTEIRO,0.000000,0.000000,0.000000
16,JOÃO GABRIEL VALENTIM ROCHA,0.000000,0.000000,0.000000
17,MURILO PRADO WEYNE,0.333333,0.666667,0.333333
18,CAIO RIBEIRO DE PAULA,0.000000,0.000000,0.000000
19,ARIEL TAMEZGUI LEVENTHAL,-0.666667,-0.333333,-0.666667
20,PEDRO CLIQUET DO AMARAL,0.000000,0.000000,0.000000
21,ANDRÉ BRITO,0.666667,0.666667,-0.333333
22,ARTHUR CISOTTO MACHADO,-0.666667,-0.666667,-0.333333
23,MARLON SILVA PEREIRA,0.666667,-0.333333,0.333333
24,RAFAEL ELI KATRI,0.000000,0.000000,0.000000
25,PEDRO BITTAR BARÃO,0.000000,0.000000,0.000000
26,FERNANDA DE OLIVEIRA PEREIRA,0.000000,0.000000,-1.000000
27,LEONARDO DA FRANÇA MOURA DE ANDRADE,NaN,NaN,NaN
28,RAFAEL COCA LEVENTHAL,NaN,NaN,NaN

In [14]:
df_medias.to_excel('sprint2_medias.xlsx')