In [1]:
import pandas as pd

In [2]:
!ls

Análise.ipynb
Avaliação Individual dos Membros (Responses).xlsx
sprint3_feedback.ipynb
sprint3_mean_calculator.ipynb

In [3]:
df = pd.read_excel('Avaliação Individual dos Membros (Responses).xlsx')

In [4]:
df.set_index('Selecione o seu Nome', inplace=True)
df.drop(['Timestamp'], axis=1, inplace=True)

In [5]:
columns = df.columns

In [6]:
df

,"Qual nível de PRODUTIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [ALBERTO MANSUR]","Qual nível de PRODUTIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [FELIPE CATAPANO]","Qual nível de PRODUTIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [FERNANDO GIUSEPPE AVILA BELTRAMO]","Qual nível de PRODUTIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [RAFAEL ELI KATRI]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [ALBERTO MANSUR]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [FELIPE CATAPANO]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [FERNANDO GIUSEPPE AVILA BELTRAMO]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [RAFAEL ELI KATRI]","Qual nível de TRANSPARÊNCIA cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [ALBERTO MANSUR]","Qual nível de TRANSPARÊNCIA cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [FELIPE CATAPANO]",...,"Qual nível de TRANSPARÊNCIA cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [MARLON SILVA PEREIRA]","Qual nível de PRODUTIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [LINCOLN RODRIGO PEREIRA MELO]","Qual nível de PRODUTIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [PEDRO CLIQUET DO AMARAL]","Qual nível de PRODUTIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [VINICIUS MATHEUS MORALES]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [LINCOLN RODRIGO PEREIRA MELO]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [PEDRO CLIQUET DO AMARAL]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [VINICIUS MATHEUS MORALES]","Qual nível de TRANSPARÊNCIA cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [LINCOLN RODRIGO PEREIRA MELO]","Qual nível de TRANSPARÊNCIA cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [PEDRO CLIQUET DO AMARAL]","Qual nível de TRANSPARÊNCIA cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [VINICIUS MATHEUS MORALES]"
Selecione o seu Nome,,,,,,,,,,,,,,,,,,,,,
PEDRO BITTAR BARÃO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ENRICCO GEMHA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
HUDSON MONTEIRO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PEDRO PAULO MORENO CAMARGO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DOM RUAN SUZANO FIGUEIRA DA SILVA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
GIOVANA CASSONI ANDRADE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ANTÔNIO AMARAL EGYDIO MARTINS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MURILO PRADO WEYNE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CAIO TRAVAIN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FELIPE CATAPANO,3.0,4.0,3.0,3.0,3.0,4.0,3.0,3.0,3.0,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
RAFAEL ELI KATRI,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
VINICIUS MATHEUS MORALES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0
CAIO RIBEIRO DE PAULA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FERNANDO GIUSEPPE AVILA BELTRAMO,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LEONARDO DA FRANÇA MOURA DE ANDRADE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
RODRIGO ANCIÃES PATELLI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
GUILHERME DOS SANTOS MARTINS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MARLON SILVA PEREIRA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ARIEL TAMEZGUI LEVENTHAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ARTHUR MARTINS DE SOUZA BARRETO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PEDRO CLIQUET DO AMARAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,4.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0
FERNANDA DE OLIVEIRA PEREIRA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ANDRÉ CORRÊA SANTOS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
JOÃO GABRIEL VALENTIM ROCHA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LINCOLN RODRIGO PEREIRA MELO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,4.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0
ANDRÉ BRITO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
new_columns = {}
for column in columns:
    # posição das palavras 'PRODUTIVIDADE', 'PROATIVIDADE', 'TRANSPARÊNCIA' no nome da coluna
    categoria = column.split()[3]
    nome = column.split('[')[-1].replace(']','')
    #removendo texto desnecessário da coluna e renomeando no padrão ex: PRODUTIVIDADE - NOME DO ALUN@
    new_columns[column] = f'{categoria} - {nome}'

In [8]:
df.rename(columns=new_columns, inplace=True)

In [9]:
alunos = list(df.index)
#Dicionário para armazenar as médias para criar um novo dataframe
data = {
    'nome':[],
    'media_produtividade':[],
    'media_proatividade':[],
    'media_transparência':[],
    'auto_produtividade':[],
    'auto_proatividade':[],
    'auto_transparência':[],
    'media':[]
}

In [10]:
categorias = ['PRODUTIVIDADE', 'PROATIVIDADE', 'TRANSPARÊNCIA']
for aluno in alunos:
    data['nome'].append(aluno)
    soma = 0
    for categoria in categorias:
        nome_coluna = f'{categoria} - {aluno}'
        media_colegas = df.loc[(df.index != aluno) ,nome_coluna].dropna().mean()
        soma += media_colegas
        
        auto_avaliacao = df.loc[(df.index == aluno) ,nome_coluna][0]
        
        data[f'media_{categoria.lower()}'].append(media_colegas)
        data[f'auto_{categoria.lower()}'].append(auto_avaliacao)
    data['media'].append(soma/3)

In [11]:
# data

In [12]:
df_medias = pd.DataFrame(data=data)

In [13]:
df_medias['dif_produtividade'] = df_medias['media_produtividade'] - df_medias['auto_produtividade']
df_medias['dif_proatividade'] = df_medias['media_proatividade'] - df_medias['auto_proatividade']
df_medias['dif_transparência'] = df_medias['media_transparência'] - df_medias['auto_transparência']

In [14]:
df_medias.loc[:,['nome','dif_produtividade','dif_proatividade','dif_transparência']]

,nome,dif_produtividade,dif_proatividade,dif_transparência
0,PEDRO BITTAR BARÃO,0.000000,0.000000,0.000000
1,ENRICCO GEMHA,1.000000,1.000000,1.000000
2,HUDSON MONTEIRO,0.000000,0.000000,0.000000
3,PEDRO PAULO MORENO CAMARGO,0.000000,0.000000,0.000000
4,DOM RUAN SUZANO FIGUEIRA DA SILVA,0.000000,0.000000,0.000000
5,GIOVANA CASSONI ANDRADE,0.000000,0.333333,0.000000
6,ANTÔNIO AMARAL EGYDIO MARTINS,0.333333,-0.666667,0.333333
7,MURILO PRADO WEYNE,0.333333,0.666667,0.333333
8,CAIO TRAVAIN,0.000000,1.000000,1.000000
9,FELIPE CATAPANO,-1.000000,-1.000000,-1.000000
10,RAFAEL ELI KATRI,0.000000,0.000000,0.000000
11,VINICIUS MATHEUS MORALES,0.000000,0.000000,0.000000
12,CAIO RIBEIRO DE PAULA,0.000000,0.000000,0.000000
13,FERNANDO GIUSEPPE AVILA BELTRAMO,0.000000,0.000000,0.000000
14,LEONARDO DA FRANÇA MOURA DE ANDRADE,0.000000,-1.000000,0.000000
15,RODRIGO ANCIÃES PATELLI,1.000000,1.000000,0.000000
16,GUILHERME DOS SANTOS MARTINS,0.000000,0.000000,0.000000
17,MARLON SILVA PEREIRA,0.333333,0.333333,0.000000
18,ARIEL TAMEZGUI LEVENTHAL,0.333333,0.666667,0.333333
19,ARTHUR MARTINS DE SOUZA BARRETO,-1.000000,-0.666667,-1.000000
20,PEDRO CLIQUET DO AMARAL,0.000000,0.000000,0.000000
21,FERNANDA DE OLIVEIRA PEREIRA,0.000000,0.000000,0.000000
22,ANDRÉ CORRÊA SANTOS,-1.000000,0.000000,0.000000
23,JOÃO GABRIEL VALENTIM ROCHA,0.000000,0.000000,0.000000
24,LINCOLN RODRIGO PEREIRA MELO,-0.500000,0.000000,0.000000
25,ANDRÉ BRITO,NaN,NaN,NaN

In [15]:
df_medias.to_excel('sprint3_medias.xlsx')