In [1]:
import pandas as pd

In [2]:
df = pd.read_excel('2023-1-sprint1-responses.xlsx')
df.set_index('Selecione o seu Nome', inplace=True)
df.drop(['Timestamp'], axis=1, inplace=True)
df.drop(['Email Address'], axis=1, inplace=True)

In [3]:
columns = df.columns

In [4]:
new_columns = {}
for column in columns:
    # posição das palavras 'PRODUTIVIDADE', 'PROATIVIDADE', 'TRANSPARÊNCIA' no nome da coluna
    categoria = column.split()[3]
    nome = column.split('[')[-1].replace(']','')
    #removendo texto desnecessário da coluna e renomeando no padrão ex: PRODUTIVIDADE - NOME DO ALUN@
    new_columns[column] = f'{categoria} - {nome}'

In [5]:
df.rename(columns=new_columns, inplace=True)

In [6]:
responder = []

In [7]:
transposed = df.T
for aluno in df.index:

    index_filter = [index for index in transposed.index if 'PRODUTIVIDADE' in index]
    if 5 in list(transposed.loc[index_filter, aluno].dropna()):
        responder.append(aluno)

In [8]:
responder

[]

In [9]:
#respostas do aluno
aluno = 'NICOLAS ENZO YASSUDA'
transposed.loc[index_filter, aluno].dropna()

PRODUTIVIDADE - GABRIELA KATSURAYAMA        4.0
PRODUTIVIDADE - GUSTAVO MENDES DA SILVA     4.0
PRODUTIVIDADE - KEVIN NAGAYUKI SHINOHARA    4.0
PRODUTIVIDADE - NICOLAS ENZO YASSUDA        4.0
Name: NICOLAS ENZO YASSUDA, dtype: float64

In [10]:
#respostas do aluno
aluno = 'NICOLAS ENZO YASSUDA'
index_aluno = [linha for linha in transposed.index if aluno in linha] 

transposed.loc[index_aluno,:]

Selecione o seu Nome,TALES IVALQUE TAVEIRA DE FREITAS,Gustavo Eliziario Stevenson de Oliveira,LUCA MIZRAHI,RODRIGO PAOLIELLO DE MEDEIROS,LUCAS HIX,JOÃO PEDRO RODRIGUES SANTOS,ARTHUR MOREIRA TAMM,LUANA WILNER ABRAMOFF,BRUNA LIMA MEINBERG,DIOGO PEREIRA LOBO,...,JOÃO ANTÔNIO GOMES GARCIA,BRUNO MARQUES LI VOLSI FALCAO,LUCAS NOVAIS DE OLIVEIRA,MATHEUS RAFFAELLE NERY CASTELLUCCI,PEDRO HENRIQUE RIZO COLPAS,PEDRO GOMES DE SÁ DRUMOND,ALBERTO MARTINS PEREIRA CARRERA,DOUGLAS PABLO,PEDRO BALBO PORTELLA,RAFAEL PASCARELLI NICCHERI
PRODUTIVIDADE - NICOLAS ENZO YASSUDA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PROATIVIDADE - NICOLAS ENZO YASSUDA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TRANSPARÊNCIA - NICOLAS ENZO YASSUDA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [75]:
index_aluno
df.loc[:,index_aluno].dropna()

,PRODUTIVIDADE - ARTHUR MARTINS DE SOUZA BARRETO,PROATIVIDADE - ARTHUR MARTINS DE SOUZA BARRETO,TRANSPARÊNCIA - ARTHUR MARTINS DE SOUZA BARRETO
Selecione o seu Nome,,,
ANTÔNIO AMARAL EGYDIO MARTINS,3.0,4.0,3.0
ARIEL TAMEZGUI LEVENTHAL,4.0,4.0,3.0
ARTHUR MARTINS DE SOUZA BARRETO,4.0,4.0,4.0
MURILO PRADO WEYNE,2.0,2.0,2.0

In [42]:
#Exemplo: pegando resposta com valor 5 em PRODUTIVIDADE
aluno = 'ANDRÉ BRITO'
5 in list(transposed.loc[index_filter, aluno].dropna())

True