In [4]:
import pandas as pd

In [5]:
df = pd.read_excel('2023-1-sprint1-responses.xlsx')

In [6]:
df.head(2)

,Timestamp,Email Address,Selecione o seu Nome,"Qual nível de PRODUTIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [ALBERTO MARTINS PEREIRA CARRERA]","Qual nível de PRODUTIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [DOUGLAS PABLO]","Qual nível de PRODUTIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [PEDRO GOMES DE SÁ DRUMOND]","Qual nível de PRODUTIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [PEDRO IVO AMARAL LIMA]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [ALBERTO MARTINS PEREIRA CARRERA]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [DOUGLAS PABLO]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [PEDRO GOMES DE SÁ DRUMOND]",...,"Qual nível de PRODUTIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [RAFAEL PASCARELLI NICCHERI]","Qual nível de PRODUTIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [TALES IVALQUE TAVEIRA DE FREITAS]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [LUCAS HIX]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [PEDRO BALBO PORTELLA]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [RAFAEL PASCARELLI NICCHERI]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [TALES IVALQUE TAVEIRA DE FREITAS]","Qual nível de TRANSPARÊNCIA cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [LUCAS HIX]","Qual nível de TRANSPARÊNCIA cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [PEDRO BALBO PORTELLA]","Qual nível de TRANSPARÊNCIA cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [RAFAEL PASCARELLI NICCHERI]","Qual nível de TRANSPARÊNCIA cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [TALES IVALQUE TAVEIRA DE FREITAS]"
0,2023-05-16 17:36:10.467,01tato02@gmail.com,TALES IVALQUE TAVEIRA DE FREITAS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0
1,2023-05-16 17:42:24.150,guoliveira255@gmail.com,Gustavo Eliziario Stevenson de Oliveira,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
df.set_index('Selecione o seu Nome', inplace=True)
df.drop(['Timestamp'], axis=1, inplace=True)
df.drop(['Email Address'], axis=1, inplace=True)

In [8]:
columns = df.columns

In [9]:
df.head()

,"Qual nível de PRODUTIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [ALBERTO MARTINS PEREIRA CARRERA]","Qual nível de PRODUTIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [DOUGLAS PABLO]","Qual nível de PRODUTIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [PEDRO GOMES DE SÁ DRUMOND]","Qual nível de PRODUTIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [PEDRO IVO AMARAL LIMA]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [ALBERTO MARTINS PEREIRA CARRERA]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [DOUGLAS PABLO]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [PEDRO GOMES DE SÁ DRUMOND]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [PEDRO IVO AMARAL LIMA]","Qual nível de TRANSPARÊNCIA cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [ALBERTO MARTINS PEREIRA CARRERA]","Qual nível de TRANSPARÊNCIA cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [DOUGLAS PABLO]",...,"Qual nível de PRODUTIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [RAFAEL PASCARELLI NICCHERI]","Qual nível de PRODUTIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [TALES IVALQUE TAVEIRA DE FREITAS]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [LUCAS HIX]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [PEDRO BALBO PORTELLA]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [RAFAEL PASCARELLI NICCHERI]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [TALES IVALQUE TAVEIRA DE FREITAS]","Qual nível de TRANSPARÊNCIA cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [LUCAS HIX]","Qual nível de TRANSPARÊNCIA cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [PEDRO BALBO PORTELLA]","Qual nível de TRANSPARÊNCIA cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [RAFAEL PASCARELLI NICCHERI]","Qual nível de TRANSPARÊNCIA cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [TALES IVALQUE TAVEIRA DE FREITAS]"
Selecione o seu Nome,,,,,,,,,,,,,,,,,,,,,
TALES IVALQUE TAVEIRA DE FREITAS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0
Gustavo Eliziario Stevenson de Oliveira,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LUCA MIZRAHI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
RODRIGO PAOLIELLO DE MEDEIROS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LUCAS HIX,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0

In [10]:
new_columns = {}
for column in columns:
    # posição das palavras 'PRODUTIVIDADE', 'PROATIVIDADE', 'TRANSPARÊNCIA' no nome da coluna
    categoria = column.split()[3]
    nome = column.split('[')[-1].replace(']','')
    #removendo texto desnecessário da coluna e renomeando no padrão ex: PRODUTIVIDADE - NOME DO ALUN@
    new_columns[column] = f'{categoria} - {nome}'

In [11]:
df.rename(columns=new_columns, inplace=True)

In [12]:
alunos = list(df.index)
#Dicionário para armazenar as médias para criar um novo dataframe
data = {
    'nome':[],
    'media_produtividade':[],
    'media_proatividade':[],
    'media_transparência':[],
    'auto_produtividade':[],
    'auto_proatividade':[],
    'auto_transparência':[],
    'media':[]
}

In [13]:
categorias = ['PRODUTIVIDADE', 'PROATIVIDADE', 'TRANSPARÊNCIA']
for aluno in alunos:
    data['nome'].append(aluno)
    soma = 0
    for categoria in categorias:
        nome_coluna = f'{categoria} - {aluno}'
        media_colegas = df.loc[(df.index != aluno) ,nome_coluna].dropna().mean()
        soma += media_colegas
        
        auto_avaliacao = df.loc[(df.index == aluno) ,nome_coluna][0]
        
        data[f'media_{categoria.lower()}'].append(media_colegas)
        data[f'auto_{categoria.lower()}'].append(auto_avaliacao)
    data['media'].append(soma/3)

In [14]:
# data

In [15]:
df_medias = pd.DataFrame(data=data)

In [16]:
df_medias['dif_produtividade'] = df_medias['media_produtividade'] - df_medias['auto_produtividade']
df_medias['dif_proatividade'] = df_medias['media_proatividade'] - df_medias['auto_proatividade']
df_medias['dif_transparência'] = df_medias['media_transparência'] - df_medias['auto_transparência']

In [17]:
df_medias.loc[:,['nome','dif_produtividade','dif_proatividade','dif_transparência']]

,nome,dif_produtividade,dif_proatividade,dif_transparência
0,TALES IVALQUE TAVEIRA DE FREITAS,0.000000,0.0,0.0
1,Gustavo Eliziario Stevenson de Oliveira,0.500000,1.0,1.0
2,LUCA MIZRAHI,0.500000,1.0,1.0
3,RODRIGO PAOLIELLO DE MEDEIROS,0.000000,0.0,0.0
4,LUCAS HIX,0.000000,0.0,0.0
5,JOÃO PEDRO RODRIGUES SANTOS,0.000000,0.0,0.0
6,ARTHUR MOREIRA TAMM,0.000000,0.0,0.0
7,LUANA WILNER ABRAMOFF,0.000000,0.0,0.0
8,BRUNA LIMA MEINBERG,0.000000,0.0,0.0
9,DIOGO PEREIRA LOBO,0.500000,0.5,0.5
10,ISABELLA DOS SANTOS DE AMORIM,0.000000,-0.5,-0.5
11,GABRIEL MENDONÇA DE MELLO HERMIDA,0.000000,0.0,0.0
12,PEDRO TOLEDO PIZA CIVITA,0.000000,0.0,0.0
13,PEDRO AUGUSTO GEVE DE MORAES LACERDA,0.000000,0.0,0.0
14,ANA LAIZ NOVAIS DE FARIAS,-0.500000,-1.0,-1.0
15,GUSTAVO MENDES DA SILVA,-0.500000,-0.5,-0.5
16,ALEXANDRE RODRIGUES SANTAROSSA,-0.500000,0.0,-0.5
17,PEDRO IVO AMARAL LIMA,0.000000,0.0,0.0
18,GABRIELA KATSURAYAMA,1.000000,1.0,1.0
19,NICOLAS ENZO YASSUDA,0.000000,0.0,0.0
20,JOÃO ANTÔNIO GOMES GARCIA,0.000000,0.0,0.0
21,BRUNO MARQUES LI VOLSI FALCAO,0.000000,-2.0,-2.0
22,LUCAS NOVAIS DE OLIVEIRA,-0.500000,-0.5,-0.5
23,MATHEUS RAFFAELLE NERY CASTELLUCCI,0.000000,0.0,0.0
24,PEDRO HENRIQUE RIZO COLPAS,0.000000,0.0,1.0
25,PEDRO GOMES DE SÁ DRUMOND,0.000000,0.0,0.0
26,ALBERTO MARTINS PEREIRA CARRERA,0.000000,0.0,0.0
27,DOUGLAS PABLO,0.333333,0.0,0.0
28,PEDRO BALBO PORTELLA,0.000000,0.0,0.0
29,RAFAEL PASCARELLI NICCHERI,0.000000,0.0,0.0

# Verificando respostas duplicadas

In [18]:
#fazer algo para identificar alunos que responderam o formulário mais de uma vez e pegar a última resposta
#verificar pessoas que não responderam

In [19]:
df_count = df_medias.groupby(['nome'])['nome'].count().to_frame('count')
df_count.loc[df_count["count"]>1,:]

Empty DataFrame
Columns: [count]
Index: []

# Salvando em arquivo

df_medias.to_excel('sprint1_medias.xlsx')

In [21]:
df_medias.shape

(30, 11)

In [22]:
df.shape

(30, 102)