# Notas

## Arrume o modo

In [9]:
debugMode = False #NÃO envia e-mails para alunos com debugMode habilitado
# Para enviar, deixe como debugMode=False

In [2]:
import pandas as pd
from jinja2 import Environment, FileSystemLoader
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from IPython.display import display

In [3]:
testes = 1
usercol = "username"

# Altere o nome do arquivo

In [4]:
nome_arquivo = 'sprint2_feedback.xlsx'

In [5]:
df = pd.read_excel(nome_arquivo)
df.head(2)

,Unnamed: 0,username,nome,feedback
0,0,gustavoeso,Gustavo Eliziario Stevenson de Oliveira,"\n Olá Gustavo, tudo bem?\n\n Segue abai..."
1,1,rodrigopm6,RODRIGO PAOLIELLO DE MEDEIROS,"\n Olá Rodrigo, tudo bem?\n\n Segue abai..."

In [6]:
password = "eeikpwsjhetneesg"


def envia(alunos):
    alunos.set_index(usercol, inplace=True)
    
    # me == my email address
    # you == recipient's email address

    dados = alunos


    for id_aluno, seq in dados.iterrows():

        text = seq['feedback']

        email = id_aluno

        me = "barbarata@insper.edu.br"

        if debugMode:
            you = "barbara.agena@al.insper.edu.br"
        else:
            you = email + "@al.insper.edu.br" #### NEutralize
            
        print(f'Enviando email -> {you}')

        # Create message container - the correct MIME type is multipart/alternative.
        msg = MIMEMultipart('alternative')
        msg['Subject'] = "TECWEB: Avaliação Individual dos Membros - Sprint 1"
        msg['From'] = me
        msg['To'] = you    

        part1 = MIMEText(text, 'plain')
    
        # Attach parts into message container.
        # According to RFC 2046, the last part of a multipart message, in this case
        # the HTML message, is best and preferred.
        msg.attach(part1)

        # Send the message via local SMTP server.
        #mail = smtplib.SMTP('smtp.gmail.com', 587)
        mail = smtplib.SMTP_SSL('smtp.gmail.com', 465)

        mail.login('tecnologias.web.insper', password)
        mail.sendmail(me, you, msg.as_string())
        mail.quit()
    
    print('Todos os emails enviados!!!')

In [7]:
df

,Unnamed: 0,username,nome,feedback
0,0,gustavoeso,Gustavo Eliziario Stevenson de Oliveira,"\n Olá Gustavo, tudo bem?\n\n Segue abai..."
1,1,rodrigopm6,RODRIGO PAOLIELLO DE MEDEIROS,"\n Olá Rodrigo, tudo bem?\n\n Segue abai..."
2,2,matheusc1,MATHEUS RAFFAELLE NERY CASTELLUCCI,"\n Olá Matheus, tudo bem?\n\n Segue abai..."
3,3,lucam1,LUCA MIZRAHI,"\n Olá Luca, tudo bem?\n\n Segue abaixo ..."
4,4,joaoprs3,JOÃO PEDRO RODRIGUES SANTOS,"\n Olá João, tudo bem?\n\n Segue abaixo ..."
5,5,albertompc,ALBERTO MARTINS PEREIRA CARRERA,"\n Olá Alberto, tudo bem?\n\n Segue abai..."
6,6,douglaspbc,DOUGLAS PABLO,"\n Olá Douglas, tudo bem?\n\n Segue abai..."
7,7,brunomlvf,BRUNO MARQUES LI VOLSI FALCAO,"\n Olá Bruno, tudo bem?\n\n Segue abaixo..."
8,8,gabrielmmh,GABRIEL MENDONÇA DE MELLO HERMIDA,"\n Olá Gabriel, tudo bem?\n\n Segue abai..."
9,9,alexandrers3,ALEXANDRE RODRIGUES SANTAROSSA,"\n Olá Alexandre, tudo bem?\n\n Segue ab..."
10,10,kevinns,KEVIN NAGAYUKI SHINOHARA,"\n Olá Kevin, tudo bem?\n\n Segue abaixo..."
11,11,pedrotpc,PEDRO TOLEDO PIZA CIVITA,"\n Olá Pedro, tudo bem?\n\n Segue abaixo..."
12,12,caioob,CAIO ORTEGA BÔA,"\n Olá Caio, tudo bem?\n\n Segue abaixo ..."
13,13,arthurmt,ARTHUR MOREIRA TAMM,"\n Olá Arthur, tudo bem?\n\n Segue abaix..."
14,15,rafaelpn1,RAFAEL PASCARELLI NICCHERI,"\n Olá Rafael, tudo bem?\n\n Segue abaix..."
15,16,joaoagg,JOÃO ANTÔNIO GOMES GARCIA,"\n Olá João, tudo bem?\n\n Segue abaixo ..."
16,17,pedroagml,PEDRO AUGUSTO GEVE DE MORAES LACERDA,"\n Olá Pedro, tudo bem?\n\n Segue abaixo..."
17,18,pedrogsd,PEDRO GOMES DE SÁ DRUMOND,"\n Olá Pedro, tudo bem?\n\n Segue abaixo..."
18,20,pedrohrc1,PEDRO HENRIQUE RIZO COLPAS,"\n Olá Pedro, tudo bem?\n\n Segue abaixo..."
19,21,gustavoms7,GUSTAVO MENDES DA SILVA,"\n Olá Gustavo, tudo bem?\n\n Segue abai..."
20,22,gabrielakk,GABRIELA KATSURAYAMA,"\n Olá Gabriela, tudo bem?\n\n Segue aba..."
21,23,nicolasey,NICOLAS ENZO YASSUDA,"\n Olá Nicolas, tudo bem?\n\n Segue abai..."
22,24,pedroial,PEDRO IVO AMARAL LIMA,"\n Olá Pedro, tudo bem?\n\n Segue abaixo..."
23,25,lucasno,LUCAS NOVAIS DE OLIVEIRA,"\n Olá Lucas, tudo bem?\n\n Segue abaixo..."
24,26,pedrobp1,PEDRO BALBO PORTELLA,"\n Olá Pedro, tudo bem?\n\n Segue abaixo..."
25,27,isabellasa,ISABELLA DOS SANTOS DE AMORIM,"\n Olá Isabella, tudo bem?\n\n Segue aba..."
26,28,diogopl1,DIOGO PEREIRA LOBO,"\n Olá Diogo, tudo bem?\n\n Segue abaixo..."
27,29,talesitf,TALES IVALQUE TAVEIRA DE FREITAS,"\n Olá Tales, tudo bem?\n\n Segue abaixo..."
28,30,juliaf1,JULIA FIGUEIREDO,"\n Olá Julia, tudo bem?\n\n Segue abaixo..."
29,31,lucash,LUCAS HIX,"\n Olá Lucas, tudo bem?\n\n Segue abaixo..."

In [10]:
if debugMode:
    envia(df[:testes])
else:
    envia(df)

Enviando email -> gustavoeso@al.insper.edu.br
Enviando email -> rodrigopm6@al.insper.edu.br
Enviando email -> matheusc1@al.insper.edu.br
Enviando email -> lucam1@al.insper.edu.br
Enviando email -> joaoprs3@al.insper.edu.br
Enviando email -> albertompc@al.insper.edu.br
Enviando email -> douglaspbc@al.insper.edu.br
Enviando email -> brunomlvf@al.insper.edu.br
Enviando email -> gabrielmmh@al.insper.edu.br
Enviando email -> alexandrers3@al.insper.edu.br
Enviando email -> kevinns@al.insper.edu.br
Enviando email -> pedrotpc@al.insper.edu.br
Enviando email -> caioob@al.insper.edu.br
Enviando email -> arthurmt@al.insper.edu.br
Enviando email -> rafaelpn1@al.insper.edu.br
Enviando email -> joaoagg@al.insper.edu.br
Enviando email -> pedroagml@al.insper.edu.br
Enviando email -> pedrogsd@al.insper.edu.br
Enviando email -> pedrohrc1@al.insper.edu.br
Enviando email -> gustavoms7@al.insper.edu.br
Enviando email -> gabrielakk@al.insper.edu.br
Enviando email -> nicolasey@al.insper.edu.br
Enviando email -> pedroial@al.insper.edu.br
Enviando email -> lucasno@al.insper.edu.br
Enviando email -> pedrobp1@al.insper.edu.br
Enviando email -> isabellasa@al.insper.edu.br
Enviando email -> diogopl1@al.insper.edu.br
Enviando email -> talesitf@al.insper.edu.br
Enviando email -> juliaf1@al.insper.edu.br
Enviando email -> lucash@al.insper.edu.br
Todos os emails enviados!!!