In [1]:
import pandas as pd

In [2]:
#fazer algo para identificar alunos que responderam o formulário mais de uma vez e pegar a última resposta
#verificar pessoas que não responderam

In [3]:
df = pd.read_excel('sprint_1_responsesv3.xlsx')

In [4]:
df.set_index('Selecione o seu Nome', inplace=True)
df.drop(['Timestamp'], axis=1, inplace=True)

In [5]:
columns = df.columns

In [6]:
df

,"Qual nível de PRODUTIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [ANDRÉ CORRÊA SANTOS]","Qual nível de PRODUTIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [PEDRO PAULO MORENO CAMARGO]","Qual nível de PRODUTIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [RAFAEL MELHADO ARAUJO LIMA]","Qual nível de PRODUTIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [ANDRÉ BARBOZA BRAGA DE MELO]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [ANDRÉ CORRÊA SANTOS]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [PEDRO PAULO MORENO CAMARGO]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [RAFAEL MELHADO ARAUJO LIMA]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [ANDRÉ BARBOZA BRAGA DE MELO]","Qual nível de TRANSPARÊNCIA cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [ANDRÉ CORRÊA SANTOS]","Qual nível de TRANSPARÊNCIA cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [PEDRO PAULO MORENO CAMARGO]",...,"Qual nível de PRODUTIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [FELIPE TRINTIM]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [THOMAS CHABRO]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [RAFAEL COCA LEVENTHAL]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [CAIO DE CAMARGO ARANHA TIERI]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [FELIPE TRINTIM]","Qual nível de TRANSPARÊNCIA cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [THOMAS CHABRO]","Qual nível de TRANSPARÊNCIA cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [RAFAEL COCA LEVENTHAL]","Qual nível de TRANSPARÊNCIA cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [CAIO DE CAMARGO ARANHA TIERI]","Qual nível de TRANSPARÊNCIA cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [FELIPE TRINTIM]","Qual nível de PRODUTIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [ALBERTO MANSUR]"
Selecione o seu Nome,,,,,,,,,,,,,,,,,,,,,
ARTHUR CISOTTO MACHADO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LUCAS GURGEL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
VICTOR LUIS GAMA DE ASSIS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ANDRÉ BRITO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
new_columns = {}
for column in columns:
    # posição das palavras 'PRODUTIVIDADE', 'PROATIVIDADE', 'TRANSPARÊNCIA' no nome da coluna
    categoria = column.split()[3]
    nome = column.split('[')[-1].replace(']','')
    #removendo texto desnecessário da coluna e renomeando no padrão ex: PRODUTIVIDADE - NOME DO ALUN@
    new_columns[column] = f'{categoria} - {nome}'

In [8]:
df.rename(columns=new_columns, inplace=True)

In [9]:
alunos = list(df.index)
#Dicionário para armazenar as médias para criar um novo dataframe
data = {
    'nome':[],
    'media_produtividade':[],
    'media_proatividade':[],
    'media_transparência':[],
    'auto_produtividade':[],
    'auto_proatividade':[],
    'auto_transparência':[],
    'media':[]
}

In [10]:
categorias = ['PRODUTIVIDADE', 'PROATIVIDADE', 'TRANSPARÊNCIA']
for aluno in alunos:
    data['nome'].append(aluno)
    soma = 0
    for categoria in categorias:
        nome_coluna = f'{categoria} - {aluno}'
        media_colegas = df.loc[(df.index != aluno) ,nome_coluna].dropna().mean()
        soma += media_colegas
        
        auto_avaliacao = df.loc[(df.index == aluno) ,nome_coluna][0]
        
        data[f'media_{categoria.lower()}'].append(media_colegas)
        data[f'auto_{categoria.lower()}'].append(auto_avaliacao)
    data['media'].append(soma/3)

In [11]:
# data

In [12]:
df_medias = pd.DataFrame(data=data)

In [13]:
df_medias['dif_produtividade'] = df_medias['media_produtividade'] - df_medias['auto_produtividade']
df_medias['dif_proatividade'] = df_medias['media_proatividade'] - df_medias['auto_proatividade']
df_medias['dif_transparência'] = df_medias['media_transparência'] - df_medias['auto_transparência']

In [14]:
df_medias.loc[:,['nome','dif_produtividade','dif_proatividade','dif_transparência']]

,nome,dif_produtividade,dif_proatividade,dif_transparência
0,ARTHUR CISOTTO MACHADO,-0.666667,-0.333333,-0.333333
1,LUCAS GURGEL,0.666667,1.000000,1.000000
2,VICTOR LUIS GAMA DE ASSIS,-0.666667,-0.333333,-0.333333
3,ANDRÉ BRITO,0.666667,-0.333333,-0.333333

In [15]:
df_medias.to_excel('sprint1_mediasv3.xlsx')