In [52]:
import pandas as pd

In [53]:
#fazer algo para identificar alunos que responderam o formulário mais de uma vez e pegar a última resposta
#verificar pessoas que não responderam

In [54]:
df = pd.read_excel('sprint_1_responsesv2.xlsx')

In [55]:
df.set_index('Selecione o seu Nome', inplace=True)
df.drop(['Timestamp'], axis=1, inplace=True)

In [56]:
columns = df.columns

In [57]:
df

,"Qual nível de PRODUTIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [ANDRÉ CORRÊA SANTOS]","Qual nível de PRODUTIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [PEDRO PAULO MORENO CAMARGO]","Qual nível de PRODUTIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [RAFAEL MELHADO ARAUJO LIMA]","Qual nível de PRODUTIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [ANDRÉ BARBOZA BRAGA DE MELO]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [ANDRÉ CORRÊA SANTOS]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [PEDRO PAULO MORENO CAMARGO]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [RAFAEL MELHADO ARAUJO LIMA]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [ANDRÉ BARBOZA BRAGA DE MELO]","Qual nível de TRANSPARÊNCIA cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [ANDRÉ CORRÊA SANTOS]","Qual nível de TRANSPARÊNCIA cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [PEDRO PAULO MORENO CAMARGO]",...,"Qual nível de PRODUTIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [FELIPE TRINTIM]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [THOMAS CHABRO]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [RAFAEL COCA LEVENTHAL]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [CAIO DE CAMARGO ARANHA TIERI]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [FELIPE TRINTIM]","Qual nível de TRANSPARÊNCIA cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [THOMAS CHABRO]","Qual nível de TRANSPARÊNCIA cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [RAFAEL COCA LEVENTHAL]","Qual nível de TRANSPARÊNCIA cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [CAIO DE CAMARGO ARANHA TIERI]","Qual nível de TRANSPARÊNCIA cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [FELIPE TRINTIM]","Qual nível de PRODUTIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [ALBERTO MANSUR]"
Selecione o seu Nome,,,,,,,,,,,,,,,,,,,,,
ANDRÉ BRITO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ANDRÉ CORRÊA SANTOS,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ANTÔNIO AMARAL EGYDIO MARTINS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ARIEL TAMEZGUI LEVENTHAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ARTHUR BOSCHINI DA FONSECA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ARTHUR CISOTTO MACHADO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ARTHUR MARTINS DE SOUZA BARRETO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CAIO DE CAMARGO ARANHA TIERI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,4.0,4.0,4.0,4.0,4.0,3.0,4.0,4.0,NaN
CAIO TRAVAIN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DOM RUAN SUZANO FIGUEIRA DA SILVA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ENRICCO GEMHA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ENZO BOZELLI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ERIC ANDREI LIMA POSSATO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FELIPE CATAPANO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0
FELIPE TRINTIM,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,4.0,NaN
FERNANDA DE OLIVEIRA PEREIRA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
FERNANDO GIUSEPPE AVILA BELTRAMO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0
GIOVANA CASSONI ANDRADE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
HUDSON MONTEIRO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
JOÃO GABRIEL VALENTIM ROCHA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LEONARDO DA FRANÇA MOURA DE ANDRADE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LINCOLN RODRIGO PEREIRA MELO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LUCAS GURGEL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MARLON SILVA PEREIRA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MURILO PRADO WEYNE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PEDRO BITTAR BARÃO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PEDRO CLIQUET DO AMARAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PEDRO PAULO MORENO CAMARGO,4.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,4.0,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
RAFAEL COCA LEVENTHAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,3.0,4.0,3.0,3.0,4.0,3.0,3.0,3.0,NaN
RAFAEL MELHADO ARAUJO LIMA,4.0,4.0,3.0,3.0,4.0,4.0,4.0,3.0,4.0,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
RODRIGO ANCIÃES PATELLI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
THOMAS CHABRO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,NaN
VICTOR LUIS GAMA DE ASSIS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
VINICIUS MATHEUS MORALES,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [58]:
new_columns = {}
for column in columns:
    # posição das palavras 'PRODUTIVIDADE', 'PROATIVIDADE', 'TRANSPARÊNCIA' no nome da coluna
    categoria = column.split()[3]
    nome = column.split('[')[-1].replace(']','')
    #removendo texto desnecessário da coluna e renomeando no padrão ex: PRODUTIVIDADE - NOME DO ALUN@
    new_columns[column] = f'{categoria} - {nome}'

In [59]:
df.rename(columns=new_columns, inplace=True)

In [60]:
alunos = list(df.index)
#Dicionário para armazenar as médias para criar um novo dataframe
data = {
    'nome':[],
    'media_produtividade':[],
    'media_proatividade':[],
    'media_transparência':[],
    'auto_produtividade':[],
    'auto_proatividade':[],
    'auto_transparência':[],
    'media':[]
}

In [61]:
categorias = ['PRODUTIVIDADE', 'PROATIVIDADE', 'TRANSPARÊNCIA']
for aluno in alunos:
    data['nome'].append(aluno)
    soma = 0
    for categoria in categorias:
        nome_coluna = f'{categoria} - {aluno}'
        media_colegas = df.loc[(df.index != aluno) ,nome_coluna].dropna().mean()
        soma += media_colegas
        
        auto_avaliacao = df.loc[(df.index == aluno) ,nome_coluna][0]
        
        data[f'media_{categoria.lower()}'].append(media_colegas)
        data[f'auto_{categoria.lower()}'].append(auto_avaliacao)
    data['media'].append(soma/3)

In [62]:
# data

In [63]:
df_medias = pd.DataFrame(data=data)

In [65]:
df_medias['dif_produtividade'] = df_medias['media_produtividade'] - df_medias['auto_produtividade']
df_medias['dif_proatividade'] = df_medias['media_proatividade'] - df_medias['auto_proatividade']
df_medias['dif_transparência'] = df_medias['media_transparência'] - df_medias['auto_transparência']

In [69]:
df_medias.loc[:,['nome','dif_produtividade','dif_proatividade','dif_transparência']]

,nome,dif_produtividade,dif_proatividade,dif_transparência
0,ANDRÉ BRITO,-1.333333,-1.333333,-0.333333
1,ANDRÉ CORRÊA SANTOS,1.000000,0.500000,1.000000
2,ANTÔNIO AMARAL EGYDIO MARTINS,0.333333,-0.666667,0.333333
3,ARIEL TAMEZGUI LEVENTHAL,0.000000,-0.666667,-1.000000
4,ARTHUR BOSCHINI DA FONSECA,-1.000000,-1.000000,-1.000000
5,ARTHUR CISOTTO MACHADO,0.000000,0.000000,-0.333333
6,ARTHUR MARTINS DE SOUZA BARRETO,-1.000000,-0.666667,-1.333333
7,CAIO DE CAMARGO ARANHA TIERI,-0.666667,-0.666667,-0.666667
8,CAIO TRAVAIN,0.500000,0.500000,0.500000
9,DOM RUAN SUZANO FIGUEIRA DA SILVA,0.000000,0.000000,0.000000
10,ENRICCO GEMHA,0.000000,0.000000,0.000000
11,ENZO BOZELLI,0.000000,0.000000,1.000000
12,ERIC ANDREI LIMA POSSATO,-0.500000,-0.500000,-0.500000
13,FELIPE CATAPANO,-1.000000,-1.000000,-1.000000
14,FELIPE TRINTIM,-1.000000,-0.666667,-0.666667
15,FERNANDA DE OLIVEIRA PEREIRA,-1.000000,0.500000,-0.500000
16,FERNANDO GIUSEPPE AVILA BELTRAMO,1.000000,1.000000,1.000000
17,GIOVANA CASSONI ANDRADE,0.500000,0.000000,0.500000
18,HUDSON MONTEIRO,0.000000,0.000000,0.000000
19,JOÃO GABRIEL VALENTIM ROCHA,0.000000,0.000000,0.000000
20,LEONARDO DA FRANÇA MOURA DE ANDRADE,0.500000,0.500000,0.500000
21,LINCOLN RODRIGO PEREIRA MELO,0.000000,0.500000,-1.000000
22,LUCAS GURGEL,1.333333,1.333333,1.000000
23,MARLON SILVA PEREIRA,-0.500000,-1.000000,0.500000
24,MURILO PRADO WEYNE,1.333333,2.000000,1.333333
25,PEDRO BITTAR BARÃO,-1.000000,-1.000000,-1.000000
26,PEDRO CLIQUET DO AMARAL,0.000000,0.000000,0.500000
27,PEDRO PAULO MORENO CAMARGO,0.500000,0.500000,-0.500000
28,RAFAEL COCA LEVENTHAL,0.666667,-0.333333,0.333333
29,RAFAEL MELHADO ARAUJO LIMA,0.000000,-1.000000,-0.500000
30,RODRIGO ANCIÃES PATELLI,0.000000,0.000000,-1.000000
31,THOMAS CHABRO,1.000000,0.666667,1.000000
32,VICTOR LUIS GAMA DE ASSIS,0.000000,0.000000,-0.333333
33,VINICIUS MATHEUS MORALES,0.000000,0.500000,0.500000

In [26]:
# df_medias.to_excel('sprint1_medias.xlsx')