In [12]:
import pandas as pd

In [13]:
df = pd.read_excel('responses_copy.xlsx')

In [14]:
df.head()

,Timestamp,Selecione o seu Nome,"Qual nível de PRODUTIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [ANDRÉ CORRÊA SANTOS]","Qual nível de PRODUTIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [PEDRO PAULO MORENO CAMARGO]","Qual nível de PRODUTIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [RAFAEL MELHADO ARAUJO LIMA]","Qual nível de PRODUTIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [ANDRÉ BARBOZA BRAGA DE MELO]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [ANDRÉ CORRÊA SANTOS]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [PEDRO PAULO MORENO CAMARGO]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [RAFAEL MELHADO ARAUJO LIMA]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [ANDRÉ BARBOZA BRAGA DE MELO]",...,"Qual nível de PRODUTIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [CAIO DE CAMARGO ARANHA TIERI]","Qual nível de PRODUTIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [FELIPE TRINTIM]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [THOMAS CHABRO]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [RAFAEL COCA LEVENTHAL]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [CAIO DE CAMARGO ARANHA TIERI]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [FELIPE TRINTIM]","Qual nível de TRANSPARÊNCIA cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [THOMAS CHABRO]","Qual nível de TRANSPARÊNCIA cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [RAFAEL COCA LEVENTHAL]","Qual nível de TRANSPARÊNCIA cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [CAIO DE CAMARGO ARANHA TIERI]","Qual nível de TRANSPARÊNCIA cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [FELIPE TRINTIM]"
0,2022-11-24 18:33:51.957,FERNANDO GIUSEPPE AVILA BELTRAMO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2022-11-24 18:42:48.613,ERIC ANDREI LIMA POSSATO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2022-11-24 19:11:26.298,GUILHERME DOS SANTOS MARTINS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2022-11-24 19:43:36.207,PEDRO PAULO MORENO CAMARGO,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2022-11-24 19:45:38.156,ANDRÉ CORRÊA SANTOS,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
df.set_index('Selecione o seu Nome', inplace=True)
# df.drop(['Timestamp'], axis=1, inplace=True)

In [17]:
df.drop(['Timestamp'], axis=1, inplace=True)

In [18]:
columns = df.columns

In [19]:
new_columns = {}
for column in columns:
    # posição das palavras 'PRODUTIVIDADE', 'PROATIVIDADE', 'TRANSPARÊNCIA' no nome da coluna
    categoria = column.split()[3]
    nome = column.split('[')[-1].replace(']','')
    #removendo texto desnecessário da coluna e renomeando no padrão ex: PRODUTIVIDADE - NOME DO ALUN@
    new_columns[column] = f'{categoria} - {nome}'

In [20]:
df.rename(columns=new_columns, inplace=True)

In [21]:
alunos = list(df.index)
#Dicionário para armazenar as médias para criar um novo dataframe
data = {
    'nome':[],
    'media_produtividade':[],
    'media_proatividade':[],
    'media_transparência':[],
    'auto_produtividade':[],
    'auto_proatividade':[],
    'auto_transparência':[],
    'media':[]
}

In [22]:
columns_ = df.columns

In [23]:
columns_sem_aluno = [column for column in columns if 'ALBERTO MANSUR' not in column]

In [24]:
columns_sem_aluno[0]

'Qual nível de PRODUTIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [ANDRÉ CORRÊA SANTOS]'

In [25]:
df.columns

Index(['PRODUTIVIDADE - ANDRÉ CORRÊA SANTOS',
       'PRODUTIVIDADE - PEDRO PAULO MORENO CAMARGO',
       'PRODUTIVIDADE - RAFAEL MELHADO ARAUJO LIMA',
       'PRODUTIVIDADE - ANDRÉ BARBOZA BRAGA DE MELO',
       'PROATIVIDADE - ANDRÉ CORRÊA SANTOS',
       'PROATIVIDADE - PEDRO PAULO MORENO CAMARGO',
       'PROATIVIDADE - RAFAEL MELHADO ARAUJO LIMA',
       'PROATIVIDADE - ANDRÉ BARBOZA BRAGA DE MELO',
       'TRANSPARÊNCIA - ANDRÉ CORRÊA SANTOS',
       'TRANSPARÊNCIA - PEDRO PAULO MORENO CAMARGO',
       ...
       'PRODUTIVIDADE - CAIO DE CAMARGO ARANHA TIERI',
       'PRODUTIVIDADE - FELIPE TRINTIM', 'PROATIVIDADE - THOMAS CHABRO',
       'PROATIVIDADE - RAFAEL COCA LEVENTHAL',
       'PROATIVIDADE - CAIO DE CAMARGO ARANHA TIERI',
       'PROATIVIDADE - FELIPE TRINTIM', 'TRANSPARÊNCIA - THOMAS CHABRO',
       'TRANSPARÊNCIA - RAFAEL COCA LEVENTHAL',
       'TRANSPARÊNCIA - CAIO DE CAMARGO ARANHA TIERI',
       'TRANSPARÊNCIA - FELIPE TRINTIM'],
      dtype='object', length=117)

In [26]:
categorias = ['PRODUTIVIDADE', 'PROATIVIDADE', 'TRANSPARÊNCIA']
for aluno in alunos:
    if aluno != 'ALBERTO MANSUR':
        data['nome'].append(aluno)
        soma = 0
        for categoria in categorias:
            nome_coluna = f'{categoria} - {aluno}'
            media_colegas = df.loc[(df.index != aluno) ,nome_coluna].dropna().mean()
            soma += media_colegas

            auto_avaliacao = df.loc[(df.index == aluno) ,nome_coluna][0]

            data[f'media_{categoria.lower()}'].append(media_colegas)
            data[f'auto_{categoria.lower()}'].append(auto_avaliacao)
        data['media'].append(soma/3)

In [27]:
# data

In [28]:
df_medias = pd.DataFrame(data=data)

In [29]:
df_medias['dif_produtividade'] = df_medias['media_produtividade'] - df_medias['auto_produtividade']
df_medias['dif_proatividade'] = df_medias['media_proatividade'] - df_medias['auto_proatividade']
df_medias['dif_transparência'] = df_medias['media_transparência'] - df_medias['auto_transparência']

In [30]:
df_medias.loc[:,['nome','dif_produtividade','dif_proatividade','dif_transparência']]

,nome,dif_produtividade,dif_proatividade,dif_transparência
0,FERNANDO GIUSEPPE AVILA BELTRAMO,0.000000,0.000000,0.000000
1,ERIC ANDREI LIMA POSSATO,-0.500000,-0.500000,-0.500000
2,GUILHERME DOS SANTOS MARTINS,0.000000,0.333333,0.333333
3,PEDRO PAULO MORENO CAMARGO,0.666667,0.666667,0.333333
4,ANDRÉ CORRÊA SANTOS,0.666667,0.666667,0.333333
5,ANTÔNIO AMARAL EGYDIO MARTINS,0.666667,-0.333333,0.666667
6,GIOVANA CASSONI ANDRADE,0.000000,0.333333,0.333333
7,ENZO BOZELLI,0.500000,0.500000,0.500000
8,RODRIGO ANCIÃES PATELLI,0.500000,0.000000,0.500000
9,VINICIUS MATHEUS MORALES,0.000000,0.000000,0.000000
10,VICTOR LUIS GAMA DE ASSIS,-0.666667,-0.666667,-0.333333
11,ARTHUR MARTINS DE SOUZA BARRETO,-1.000000,-0.666667,-1.000000
12,LUCAS GURGEL,0.666667,0.666667,1.000000
13,LINCOLN RODRIGO PEREIRA MELO,0.500000,0.000000,0.000000
14,DOM RUAN SUZANO FIGUEIRA DA SILVA,0.000000,0.000000,0.000000
15,HUDSON MONTEIRO,0.000000,0.000000,0.000000
16,JOÃO GABRIEL VALENTIM ROCHA,0.000000,0.000000,0.000000
17,MURILO PRADO WEYNE,0.333333,0.666667,0.333333
18,CAIO RIBEIRO DE PAULA,0.000000,0.000000,0.000000
19,ARIEL TAMEZGUI LEVENTHAL,-0.666667,-0.333333,-0.666667
20,PEDRO CLIQUET DO AMARAL,0.000000,0.000000,0.000000
21,ANDRÉ BRITO,0.666667,0.666667,-0.333333
22,ARTHUR CISOTTO MACHADO,-0.666667,-0.666667,-0.333333
23,MARLON SILVA PEREIRA,0.666667,-0.333333,0.333333
24,RAFAEL ELI KATRI,0.000000,0.000000,0.000000
25,PEDRO BITTAR BARÃO,0.000000,0.000000,0.000000
26,FERNANDA DE OLIVEIRA PEREIRA,0.000000,0.000000,-1.000000
27,LEONARDO DA FRANÇA MOURA DE ANDRADE,-0.333333,0.666667,0.666667
28,RAFAEL COCA LEVENTHAL,0.333333,0.666667,0.666667
29,THOMAS CHABRO,0.666667,0.333333,0.666667
30,FELIPE TRINTIM,-1.000000,-0.666667,-0.666667
31,ARTHUR BOSCHINI DA FONSECA,0.333333,0.666667,-0.333333
32,CAIO TRAVAIN,0.666667,-0.666667,0.666667
33,JOSEPH KALLAS NETO,0.000000,-0.666667,-0.666667
34,RAFAEL MELHADO ARAUJO LIMA,-1.000000,-1.000000,-1.000000
35,CAIO DE CAMARGO ARANHA TIERI,-0.666667,0.333333,-0.666667
36,ANDRÉ BARBOZA BRAGA DE MELO,1.000000,0.000000,0.333333
37,ENRICCO GEMHA,-0.500000,-0.500000,-0.500000

In [31]:
df_medias.to_excel('sprint2_medias.xlsx')