In [1]:
import pandas as pd

## Carregando nomes e usernames dos alunos

In [2]:
alunos_username = pd.read_excel('alunos.xlsx')
alunos_username.set_index('full_name', inplace=True)

In [3]:
alunos_username.head(2)

                                     username
full_name
ALBERTO MARTINS PEREIRA CARRERA    albertompc
ALEXANDRE RODRIGUES SANTAROSSA   alexandrers3

## Carregando médias da sprint

In [4]:
df = pd.read_excel('sprint2_medias.xlsx')

In [5]:
df.head(2)

,Unnamed: 0,nome,media_produtividade,media_proatividade,media_transparência,auto_produtividade,auto_proatividade,auto_transparência,media,dif_produtividade,dif_proatividade,dif_transparência
0,0,Gustavo Eliziario Stevenson de Oliveira,3.5,3.5,3.5,3,3,3,3.5,0.5,0.5,0.5
1,1,RODRIGO PAOLIELLO DE MEDEIROS,3.0,3.0,3.0,3,3,3,3.0,0.0,0.0,0.0

In [6]:
df.set_index('nome', inplace=True)
df.drop(['Unnamed: 0'], axis=1, inplace=True)

In [7]:
df.head(2)

,media_produtividade,media_proatividade,media_transparência,auto_produtividade,auto_proatividade,auto_transparência,media,dif_produtividade,dif_proatividade,dif_transparência
nome,,,,,,,,,,
Gustavo Eliziario Stevenson de Oliveira,3.5,3.5,3.5,3,3,3,3.5,0.5,0.5,0.5
RODRIGO PAOLIELLO DE MEDEIROS,3.0,3.0,3.0,3,3,3,3.0,0.0,0.0,0.0

## Realizando join para pegar o username

nem precisa

junto = df.join(alunos, how='inner')
junto.head(2)

In [8]:
alunos_username.shape

(35, 1)

In [9]:
df.shape

(32, 10)

junto.shape

___

In [10]:
def texto_diferenca(diferenca):
    if diferenca == 0:
        return 'Ou seja, a visão dos colegas sobre você foi igual.\n    Sua percepção parece correta.'
    elif diferenca > 0:
        return 'Ou seja, a visão dos colegas sobre você foi superior.'
    elif diferenca < 0 and diferenca <= -1:
        return 'Ou seja, a visão dos colegas sobre você foi um pouco inferior.\n    Não muito, mas vale uma reflexão.'
    else:
        return 'Ou seja, a visão dos colegas sobre você foi um pouco inferior, vale uma reflexão.'

In [11]:
def generate_feedback(aluno):
    first_name = aluno.split()[0].capitalize()
    AUTO_PRODUTIVIDADE = round(df.loc[aluno,"auto_produtividade"], 2)
    MEDIA_PRODUTIVIDADE = round(df.loc[aluno,"media_produtividade"],2)
    DIFERENCA_PRODUTIVIDADE = round(MEDIA_PRODUTIVIDADE - AUTO_PRODUTIVIDADE ,2)
    
    AUTO_PROATIVIDADE = round(df.loc[aluno,"auto_proatividade"], 2)
    MEDIA_PROATIVIDADE = round(df.loc[aluno,"media_proatividade"],2)
    DIFERENCA_PROATIVIDADE = round(MEDIA_PROATIVIDADE - AUTO_PROATIVIDADE,2)
    
    AUTO_TRANSPARENCIA = round(df.loc[aluno,"auto_transparência"], 2)
    MEDIA_TRANSPARENCIA = round(df.loc[aluno,"media_transparência"],2)
    DIFERENCA_TRANSPARENCIA = round(MEDIA_TRANSPARENCIA - AUTO_TRANSPARENCIA,2)
    
    texto = f'''
    Olá {first_name}, tudo bem?

    Segue abaixo seu feedback de grupo da Sprint 1.

    Lembrete: Um membro é considerado bem avaliado quando obtém uma média entre 3 e 5 em produtividade,
    uma média entre 3 e 4 em proatividade em uma média entre 3 e 4 em transparência.

    A diferença entre 3 e 4, sozinha, não faz diferença para
    nota. O nível 4 deve ser usado para reconhecer o esforço
    de membros específicos.

    Produtividade:
    -------------

    Nível que você atribuiu a si mesmo: {AUTO_PRODUTIVIDADE}

    Média dos níveis que os colegas atribuíram a você: {MEDIA_PRODUTIVIDADE}

    Diferença: {DIFERENCA_PRODUTIVIDADE}

    {texto_diferenca(DIFERENCA_PRODUTIVIDADE)}


    Proatividade:
    ------------

    Nível que você atribuiu a si mesmo: {AUTO_PROATIVIDADE}

    Média dos níveis que os colegas atribuíram a você: {MEDIA_PROATIVIDADE}

    Diferença: {DIFERENCA_PROATIVIDADE}

    {texto_diferenca(DIFERENCA_PROATIVIDADE)}


    Transparência
    -------------

    Nível que você atribuiu a si mesmo: {AUTO_TRANSPARENCIA}

    Média dos níveis que os colegas atribuíram a você: {MEDIA_TRANSPARENCIA}

    Diferença: {DIFERENCA_TRANSPARENCIA}

    {texto_diferenca(DIFERENCA_TRANSPARENCIA)}
    
    
    Esteja à vontade para perguntar em caso de quaisquer dúvidas.
    
    Abraços,
    Bárbara Agena

'''
    return texto

In [12]:
data = {
    'username':[],
    'nome':[],
    'feedback':[]
    
}

In [13]:
alunos = list(df.index)
for aluno in alunos:
    data['username'].append(alunos_username.loc[aluno, 'username'])
    data['nome'].append(aluno)
    data['feedback'].append(generate_feedback(aluno))

In [14]:
data

{'username': ['gustavoeso',
  'rodrigopm6',
  'matheusc1',
  'lucam1',
  'joaoprs3',
  'albertompc',
  'douglaspbc',
  'brunomlvf',
  'gabrielmmh',
  'alexandrers3',
  'kevinns',
  'pedrotpc',
  'caioob',
  'arthurmt',
  'luanawa',
  'rafaelpn1',
  'joaoagg',
  'pedroagml',
  'pedrogsd',
  'brunalm2',
  'pedrohrc1',
  'gustavoms7',
  'gabrielakk',
  'nicolasey',
  'pedroial',
  'lucasno',
  'pedrobp1',
  'isabellasa',
  'diogopl1',
  'talesitf',
  'juliaf1',
  'lucash'],
 'nome': ['Gustavo Eliziario Stevenson de Oliveira',
  'RODRIGO PAOLIELLO DE MEDEIROS',
  'MATHEUS RAFFAELLE NERY CASTELLUCCI',
  'LUCA MIZRAHI',
  'JOÃO PEDRO RODRIGUES SANTOS',
  'ALBERTO MARTINS PEREIRA CARRERA',
  'DOUGLAS PABLO',
  'BRUNO MARQUES LI VOLSI FALCAO',
  'GABRIEL MENDONÇA DE MELLO HERMIDA',
  'ALEXANDRE RODRIGUES SANTAROSSA',
  'KEVIN NAGAYUKI SHINOHARA',
  'PEDRO TOLEDO PIZA CIVITA',
  'CAIO ORTEGA BÔA',
  'ARTHUR MOREIRA TAMM',
  'LUANA WILNER ABRAMOFF',
  'RAFAEL PASCARELLI NICCHERI',
  'JOÃO ANTÔNIO GOMES GARCIA',
  'PEDRO AUGUSTO GEVE DE MORAES LACERDA',
  'PEDRO GOMES DE SÁ DRUMOND',
  'BRUNA LIMA MEINBERG',
  'PEDRO HENRIQUE RIZO COLPAS',
  'GUSTAVO MENDES DA SILVA',
  'GABRIELA KATSURAYAMA',
  'NICOLAS ENZO YASSUDA',
  'PEDRO IVO AMARAL LIMA',
  'LUCAS NOVAIS DE OLIVEIRA',
  'PEDRO BALBO PORTELLA',
  'ISABELLA DOS SANTOS DE AMORIM',
  'DIOGO PEREIRA LOBO',
  'TALES IVALQUE TAVEIRA DE FREITAS',
  'JULIA FIGUEIREDO',
  'LUCAS HIX'],
 'feedback': ['\n    Olá Gustavo, tudo bem?\n\n    Segue abaixo seu feedback de grupo da Sprint 1.\n\n    Lembrete: Um membro é considerado bem avaliado quando obtém uma média entre 3 e 5 em produtividade,\n    uma média entre 3 e 4 em proatividade em uma média entre 3 e 4 em transparência.\n\n    A diferença entre 3 e 4, sozinha, não faz diferença para\n    nota. O nível 4 deve ser usado para reconhecer o esforço\n    de membros específicos.\n\n    Produtividade:\n    -------------\n\n    Nível que você atribuiu a si mesmo: 3\n\n    Média dos níveis que os colegas atribuíram a você: 3.5\n\n    Diferença: 0.5\n\n    Ou seja, a visão dos colegas sobre você foi superior.\n\n\n    Proatividade:\n    ------------\n\n    Nível que você atribuiu a si mesmo: 3\n\n    Média dos níveis que os colegas atribuíram a você: 3.5\n\n    Diferença: 0.5\n\n    Ou seja, a visão dos colegas sobre você foi superior.\n\n\n    Transparência\n    -------------\n\n    Nível que você atribuiu a si mesmo: 3\n\n    Média dos níveis que os colegas atribuíram a você: 3.5\n\n    Diferença: 0.5\n\n    Ou seja, a visão dos colegas sobre você foi superior.\n    \n    \n    Esteja à vontade para perguntar em caso de quaisquer dúvidas.\n    \n    Abraços,\n    Bárbara Agena\n\n',
  '\n    Olá Rodrigo, tudo bem?\n\n    Segue abaixo seu feedback de grupo da Sprint 1.\n\n    Lembrete: Um membro é considerado bem avaliado quando obtém uma média entre 3 e 5 em produtividade,\n    uma média entre 3 e 4 em proatividade em uma média entre 3 e 4 em transparência.\n\n    A diferença entre 3 e 4, sozinha, não faz diferença para\n    nota. O nível 4 deve ser usado para reconhecer o esforço\n    de membros específicos.\n\n    Produtividade:\n    -------------\n\n    Nível que você atribuiu a si mesmo: 3\n\n    Média dos níveis que os colegas atribuíram a você: 3.0\n\n    Diferença: 0.0\n\n    Ou seja, a visão dos colegas sobre você foi igual.\n    Sua percepção parece correta.\n\n\n    Proatividade:\n    ------------\n\n    Nível que você atribuiu a si mesmo: 3\n\n    Média dos níveis que os colegas atribuíram a você: 3.0\n\n    Diferença: 0.0\n\n    Ou seja, a visão dos colegas sobre você foi igual.\n    Sua percepção parece correta.\n\n\n    Transparência\n    -------------\n\n    Nível que você atribuiu a si mesmo: 3\n\n    Média dos níveis que os colegas atribuíram a você: 3.0\n\n    Diferença: 0.0\n\n    Ou seja, a visão dos colegas sobre você foi igual.\n    Sua percepção parece correta.\n    \n    \n    Esteja à vontade para perguntar em caso de quaisquer dúvidas.\n    \n    Abraços,\n    Bárbara Agena\n\n',
  '\n    Olá Matheus, tudo bem?\n\n    Segue abaixo seu feedback de grupo da Sprint 1.\n\n    Lembrete: Um membro é considerado bem avaliado quando obtém uma média entre 3 e 5 em produtividade,\n    uma média entre 3 e 4 em proatividade em uma média entre 3 e 4 em transparência.\n\n    A diferença entre 3 e 4, sozinha, não faz diferença para\n    nota. O nível 4 deve ser usado para reconhecer o esforço\n    de membros específicos.\n\n    Produtividade:\n    -------------\n\n    Nível que você atribuiu a si mesmo: 3\n\n    Média dos níveis que os colegas atribuíram a você: 3.0\n\n    Diferença: 0.0\n\n    Ou seja, a visão dos colegas sobre você foi igual.\n    Sua percepção parece correta.\n\n\n    Proatividade:\n    ------------\n\n    Nível que você atribuiu a si mesmo: 3\n\n    Média dos níveis que os colegas atribuíram a você: 3.0\n\n    Diferença: 0.0\n\n    Ou seja, a visão dos colegas sobre você foi igual.\n    Sua percepção parece correta.\n\n\n    Transparência\n    -------------\n\n    Nível que você atribuiu a si mesmo: 3\n\n    Média dos níveis que os colegas atribuíram a você: 3.0\n\n    Diferença: 0.0\n\n    Ou seja, a visão dos colegas sobre você foi igual.\n    Sua percepção parece correta.\n    \n    \n    Esteja à vontade para perguntar em caso de quaisquer dúvidas.\n    \n    Abraços,\n    Bárbara Agena\n\n',
  '\n    Olá Luca, tudo bem?\n\n    Segue abaixo seu feedback de grupo da Sprint 1.\n\n    Lembrete: Um membro é considerado bem avaliado quando obtém uma média entre 3 e 5 em produtividade,\n    uma média entre 3 e 4 em proatividade em uma média entre 3 e 4 em transparência.\n\n    A diferença entre 3 e 4, sozinha, não faz diferença para\n    nota. O nível 4 deve ser usado para reconhecer o esforço\n    de membros específicos.\n\n    Produtividade:\n    -------------\n\n    Nível que você atribuiu a si mesmo: 3\n\n    Média dos níveis que os colegas atribuíram a você: 3.5\n\n    Diferença: 0.5\n\n    Ou seja, a visão dos colegas sobre você foi superior.\n\n\n    Proatividade:\n    ------------\n\n    Nível que você atribuiu a si mesmo: 3\n\n    Média dos níveis que os colegas atribuíram a você: 3.5\n\n    Diferença: 0.5\n\n    Ou seja, a visão dos colegas sobre você foi superior.\n\n\n    Transparência\n    -------------\n\n    Nível que você atribuiu a si mesmo: 3\n\n    Média dos níveis que os colegas atribuíram a você: 3.5\n\n    Diferença: 0.5\n\n    Ou seja, a visão dos colegas sobre você foi superior.\n    \n    \n    Esteja à vontade para perguntar em caso de quaisquer dúvidas.\n    \n    Abraços,\n    Bárbara Agena\n\n',
  '\n    Olá João, tudo bem?\n\n    Segue abaixo seu feedback de grupo da Sprint 1.\n\n    Lembrete: Um membro é considerado bem avaliado quando obtém uma média entre 3 e 5 em produtividade,\n    uma média entre 3 e 4 em proatividade em uma média entre 3 e 4 em transparência.\n\n    A diferença entre 3 e 4, sozinha, não faz diferença para\n    nota. O nível 4 deve ser usado para reconhecer o esforço\n    de membros específicos.\n\n    Produtividade:\n    -------------\n\n    Nível que você atribuiu a si mesmo: 3\n\n    Média dos níveis que os colegas atribuíram a você: 3.0\n\n    Diferença: 0.0\n\n    Ou seja, a visão dos colegas sobre você foi igual.\n    Sua percepção parece correta.\n\n\n    Proatividade:\n    ------------\n\n    Nível que você atribuiu a si mesmo: 3\n\n    Média dos níveis que os colegas atribuíram a você: 3.0\n\n    Diferença: 0.0\n\n    Ou seja, a visão dos colegas sobre você foi igual.\n    Sua percepção parece correta.\n\n\n    Transparência\n    -------------\n\n    Nível que você atribuiu a si mesmo: 3\n\n    Média dos níveis que os colegas atribuíram a você: 3.0\n\n    Diferença: 0.0\n\n    Ou seja, a visão dos colegas sobre você foi igual.\n    Sua percepção parece correta.\n    \n    \n    Esteja à vontade para perguntar em caso de quaisquer dúvidas.\n    \n    Abraços,\n    Bárbara Agena\n\n',
  '\n    Olá Alberto, tudo bem?\n\n    Segue abaixo seu feedback de grupo da Sprint 1.\n\n    Lembrete: Um membro é considerado bem avaliado quando obtém uma média entre 3 e 5 em produtividade,\n    uma média entre 3 e 4 em proatividade em uma média entre 3 e 4 em transparência.\n\n    A diferença entre 3 e 4, sozinha, não faz diferença para\n    nota. O nível 4 deve ser usado para reconhecer o esforço\n    de membros específicos.\n\n    Produtividade:\n    -------------\n\n    Nível que você atribuiu a si mesmo: 3\n\n    Média dos níveis que os colegas atribuíram a você: 3.0\n\n    Diferença: 0.0\n\n    Ou seja, a visão dos colegas sobre você foi igual.\n    Sua percepção parece correta.\n\n\n    Proatividade:\n    ------------\n\n    Nível que você atribuiu a si mesmo: 3\n\n    Média dos níveis que os colegas atribuíram a você: 3.0\n\n    Diferença: 0.0\n\n    Ou seja, a visão dos colegas sobre você foi igual.\n    Sua percepção parece correta.\n\n\n    Transparência\n    -------------\n\n    Nível que você atribuiu a si mesmo: 3\n\n    Média dos níveis que os colegas atribuíram a você: 3.0\n\n    Diferença: 0.0\n\n    Ou seja, a visão dos colegas sobre você foi igual.\n    Sua percepção parece correta.\n    \n    \n    Esteja à vontade para perguntar em caso de quaisquer dúvidas.\n    \n    Abraços,\n    Bárbara Agena\n\n',
  '\n    Olá Douglas, tudo bem?\n\n    Segue abaixo seu feedback de grupo da Sprint 1.\n\n    Lembrete: Um membro é considerado bem avaliado quando obtém uma média entre 3 e 5 em produtividade,\n    uma média entre 3 e 4 em proatividade em uma média entre 3 e 4 em transparência.\n\n    A diferença entre 3 e 4, sozinha, não faz diferença para\n    nota. O nível 4 deve ser usado para reconhecer o esforço\n    de membros específicos.\n\n    Produtividade:\n    -------------\n\n    Nível que você atribuiu a si mesmo: 3\n\n    Média dos níveis que os colegas atribuíram a você: 3.0\n\n    Diferença: 0.0\n\n    Ou seja, a visão dos colegas sobre você foi igual.\n    Sua percepção parece correta.\n\n\n    Proatividade:\n    ------------\n\n    Nível que você atribuiu a si mesmo: 3\n\n    Média dos níveis que os colegas atribuíram a você: 3.0\n\n    Diferença: 0.0\n\n    Ou seja, a visão dos colegas sobre você foi igual.\n    Sua percepção parece correta.\n\n\n    Transparência\n    -------------\n\n    Nível que você atribuiu a si mesmo: 3\n\n    Média dos níveis que os colegas atribuíram a você: 3.0\n\n    Diferença: 0.0\n\n    Ou seja, a visão dos colegas sobre você foi igual.\n    Sua percepção parece correta.\n    \n    \n    Esteja à vontade para perguntar em caso de quaisquer dúvidas.\n    \n    Abraços,\n    Bárbara Agena\n\n',
  '\n    Olá Bruno, tudo bem?\n\n    Segue abaixo seu feedback de grupo da Sprint 1.\n\n    Lembrete: Um membro é considerado bem avaliado quando obtém uma média entre 3 e 5 em produtividade,\n    uma média entre 3 e 4 em proatividade em uma média entre 3 e 4 em transparência.\n\n    A diferença entre 3 e 4, sozinha, não faz diferença para\n    nota. O nível 4 deve ser usado para reconhecer o esforço\n    de membros específicos.\n\n    Produtividade:\n    -------------\n\n    Nível que você atribuiu a si mesmo: 3\n\n    Média dos níveis que os colegas atribuíram a você: 3.0\n\n    Diferença: 0.0\n\n    Ou seja, a visão dos colegas sobre você foi igual.\n    Sua percepção parece correta.\n\n\n    Proatividade:\n    ------------\n\n    Nível que você atribuiu a si mesmo: 4\n\n    Média dos níveis que os colegas atribuíram a você: 3.0\n\n    Diferença: -1.0\n\n    Ou seja, a visão dos colegas sobre você foi um pouco inferior.\n    Não muito, mas vale uma reflexão.\n\n\n    Transparência\n    -------------\n\n    Nível que você atribuiu a si mesmo: 4\n\n    Média dos níveis que os colegas atribuíram a você: 3.0\n\n    Diferença: -1.0\n\n    Ou seja, a visão dos colegas sobre você foi um pouco inferior.\n    Não muito, mas vale uma reflexão.\n    \n    \n    Esteja à vontade para perguntar em caso de quaisquer dúvidas.\n    \n    Abraços,\n    Bárbara Agena\n\n',
  '\n    Olá Gabriel, tudo bem?\n\n    Segue abaixo seu feedback de grupo da Sprint 1.\n\n    Lembrete: Um membro é considerado bem avaliado quando obtém uma média entre 3 e 5 em produtividade,\n    uma média entre 3 e 4 em proatividade em uma média entre 3 e 4 em transparência.\n\n    A diferença entre 3 e 4, sozinha, não faz diferença para\n    nota. O nível 4 deve ser usado para reconhecer o esforço\n    de membros específicos.\n\n    Produtividade:\n    -------------\n\n    Nível que você atribuiu a si mesmo: 4\n\n    Média dos níveis que os colegas atribuíram a você: 4.0\n\n    Diferença: 0.0\n\n    Ou seja, a visão dos colegas sobre você foi igual.\n    Sua percepção parece correta.\n\n\n    Proatividade:\n    ------------\n\n    Nível que você atribuiu a si mesmo: 4\n\n    Média dos níveis que os colegas atribuíram a você: 4.0\n\n    Diferença: 0.0\n\n    Ou seja, a visão dos colegas sobre você foi igual.\n    Sua percepção parece correta.\n\n\n    Transparência\n    -------------\n\n    Nível que você atribuiu a si mesmo: 4\n\n    Média dos níveis que os colegas atribuíram a você: 4.0\n\n    Diferença: 0.0\n\n    Ou seja, a visão dos colegas sobre você foi igual.\n    Sua percepção parece correta.\n    \n    \n    Esteja à vontade para perguntar em caso de quaisquer dúvidas.\n    \n    Abraços,\n    Bárbara Agena\n\n',
  '\n    Olá Alexandre, tudo bem?\n\n    Segue abaixo seu feedback de grupo da Sprint 1.\n\n    Lembrete: Um membro é considerado bem avaliado quando obtém uma média entre 3 e 5 em produtividade,\n    uma média entre 3 e 4 em proatividade em uma média entre 3 e 4 em transparência.\n\n    A diferença entre 3 e 4, sozinha, não faz diferença para\n    nota. O nível 4 deve ser usado para reconhecer o esforço\n    de membros específicos.\n\n    Produtividade:\n    -------------\n\n    Nível que você atribuiu a si mesmo: 4\n\n    Média dos níveis que os colegas atribuíram a você: 4.0\n\n    Diferença: 0.0\n\n    Ou seja, a visão dos colegas sobre você foi igual.\n    Sua percepção parece correta.\n\n\n    Proatividade:\n    ------------\n\n    Nível que você atribuiu a si mesmo: 4\n\n    Média dos níveis que os colegas atribuíram a você: 4.0\n\n    Diferença: 0.0\n\n    Ou seja, a visão dos colegas sobre você foi igual.\n    Sua percepção parece correta.\n\n\n    Transparência\n    -------------\n\n    Nível que você atribuiu a si mesmo: 4\n\n    Média dos níveis que os colegas atribuíram a você: 4.0\n\n    Diferença: 0.0\n\n    Ou seja, a visão dos colegas sobre você foi igual.\n    Sua percepção parece correta.\n    \n    \n    Esteja à vontade para perguntar em caso de quaisquer dúvidas.\n    \n    Abraços,\n    Bárbara Agena\n\n',
  '\n    Olá Kevin, tudo bem?\n\n    Segue abaixo seu feedback de grupo da Sprint 1.\n\n    Lembrete: Um membro é considerado bem avaliado quando obtém uma média entre 3 e 5 em produtividade,\n    uma média entre 3 e 4 em proatividade em uma média entre 3 e 4 em transparência.\n\n    A diferença entre 3 e 4, sozinha, não faz diferença para\n    nota. O nível 4 deve ser usado para reconhecer o esforço\n    de membros específicos.\n\n    Produtividade:\n    -------------\n\n    Nível que você atribuiu a si mesmo: 3\n\n    Média dos níveis que os colegas atribuíram a você: 3.67\n\n    Diferença: 0.67\n\n    Ou seja, a visão dos colegas sobre você foi superior.\n\n\n    Proatividade:\n    ------------\n\n    Nível que você atribuiu a si mesmo: 3\n\n    Média dos níveis que os colegas atribuíram a você: 3.67\n\n    Diferença: 0.67\n\n    Ou seja, a visão dos colegas sobre você foi superior.\n\n\n    Transparência\n    -------------\n\n    Nível que você atribuiu a si mesmo: 3\n\n    Média dos níveis que os colegas atribuíram a você: 3.67\n\n    Diferença: 0.67\n\n    Ou seja, a visão dos colegas sobre você foi superior.\n    \n    \n    Esteja à vontade para perguntar em caso de quaisquer dúvidas.\n    \n    Abraços,\n    Bárbara Agena\n\n',
  '\n    Olá Pedro, tudo bem?\n\n    Segue abaixo seu feedback de grupo da Sprint 1.\n\n    Lembrete: Um membro é considerado bem avaliado quando obtém uma média entre 3 e 5 em produtividade,\n    uma média entre 3 e 4 em proatividade em uma média entre 3 e 4 em transparência.\n\n    A diferença entre 3 e 4, sozinha, não faz diferença para\n    nota. O nível 4 deve ser usado para reconhecer o esforço\n    de membros específicos.\n\n    Produtividade:\n    -------------\n\n    Nível que você atribuiu a si mesmo: 4\n\n    Média dos níveis que os colegas atribuíram a você: 4.0\n\n    Diferença: 0.0\n\n    Ou seja, a visão dos colegas sobre você foi igual.\n    Sua percepção parece correta.\n\n\n    Proatividade:\n    ------------\n\n    Nível que você atribuiu a si mesmo: 4\n\n    Média dos níveis que os colegas atribuíram a você: 4.0\n\n    Diferença: 0.0\n\n    Ou seja, a visão dos colegas sobre você foi igual.\n    Sua percepção parece correta.\n\n\n    Transparência\n    -------------\n\n    Nível que você atribuiu a si mesmo: 4\n\n    Média dos níveis que os colegas atribuíram a você: 4.0\n\n    Diferença: 0.0\n\n    Ou seja, a visão dos colegas sobre você foi igual.\n    Sua percepção parece correta.\n    \n    \n    Esteja à vontade para perguntar em caso de quaisquer dúvidas.\n    \n    Abraços,\n    Bárbara Agena\n\n',
  '\n    Olá Caio, tudo bem?\n\n    Segue abaixo seu feedback de grupo da Sprint 1.\n\n    Lembrete: Um membro é considerado bem avaliado quando obtém uma média entre 3 e 5 em produtividade,\n    uma média entre 3 e 4 em proatividade em uma média entre 3 e 4 em transparência.\n\n    A diferença entre 3 e 4, sozinha, não faz diferença para\n    nota. O nível 4 deve ser usado para reconhecer o esforço\n    de membros específicos.\n\n    Produtividade:\n    -------------\n\n    Nível que você atribuiu a si mesmo: 4\n\n    Média dos níveis que os colegas atribuíram a você: 4.0\n\n    Diferença: 0.0\n\n    Ou seja, a visão dos colegas sobre você foi igual.\n    Sua percepção parece correta.\n\n\n    Proatividade:\n    ------------\n\n    Nível que você atribuiu a si mesmo: 4\n\n    Média dos níveis que os colegas atribuíram a você: 4.0\n\n    Diferença: 0.0\n\n    Ou seja, a visão dos colegas sobre você foi igual.\n    Sua percepção parece correta.\n\n\n    Transparência\n    -------------\n\n    Nível que você atribuiu a si mesmo: 4\n\n    Média dos níveis que os colegas atribuíram a você: 4.0\n\n    Diferença: 0.0\n\n    Ou seja, a visão dos colegas sobre você foi igual.\n    Sua percepção parece correta.\n    \n    \n    Esteja à vontade para perguntar em caso de quaisquer dúvidas.\n    \n    Abraços,\n    Bárbara Agena\n\n',

In [15]:
feed = pd.DataFrame(data=data)

In [17]:
feed.to_excel('sprint2_feedback.xlsx')

In [18]:
feed

,username,nome,feedback
0,gustavoeso,Gustavo Eliziario Stevenson de Oliveira,"\n Olá Gustavo, tudo bem?\n\n Segue abai..."
1,rodrigopm6,RODRIGO PAOLIELLO DE MEDEIROS,"\n Olá Rodrigo, tudo bem?\n\n Segue abai..."
2,matheusc1,MATHEUS RAFFAELLE NERY CASTELLUCCI,"\n Olá Matheus, tudo bem?\n\n Segue abai..."
3,lucam1,LUCA MIZRAHI,"\n Olá Luca, tudo bem?\n\n Segue abaixo ..."
4,joaoprs3,JOÃO PEDRO RODRIGUES SANTOS,"\n Olá João, tudo bem?\n\n Segue abaixo ..."
5,albertompc,ALBERTO MARTINS PEREIRA CARRERA,"\n Olá Alberto, tudo bem?\n\n Segue abai..."
6,douglaspbc,DOUGLAS PABLO,"\n Olá Douglas, tudo bem?\n\n Segue abai..."
7,brunomlvf,BRUNO MARQUES LI VOLSI FALCAO,"\n Olá Bruno, tudo bem?\n\n Segue abaixo..."
8,gabrielmmh,GABRIEL MENDONÇA DE MELLO HERMIDA,"\n Olá Gabriel, tudo bem?\n\n Segue abai..."
9,alexandrers3,ALEXANDRE RODRIGUES SANTAROSSA,"\n Olá Alexandre, tudo bem?\n\n Segue ab..."
10,kevinns,KEVIN NAGAYUKI SHINOHARA,"\n Olá Kevin, tudo bem?\n\n Segue abaixo..."
11,pedrotpc,PEDRO TOLEDO PIZA CIVITA,"\n Olá Pedro, tudo bem?\n\n Segue abaixo..."
12,caioob,CAIO ORTEGA BÔA,"\n Olá Caio, tudo bem?\n\n Segue abaixo ..."
13,arthurmt,ARTHUR MOREIRA TAMM,"\n Olá Arthur, tudo bem?\n\n Segue abaix..."
14,luanawa,LUANA WILNER ABRAMOFF,"\n Olá Luana, tudo bem?\n\n Segue abaixo..."
15,rafaelpn1,RAFAEL PASCARELLI NICCHERI,"\n Olá Rafael, tudo bem?\n\n Segue abaix..."
16,joaoagg,JOÃO ANTÔNIO GOMES GARCIA,"\n Olá João, tudo bem?\n\n Segue abaixo ..."
17,pedroagml,PEDRO AUGUSTO GEVE DE MORAES LACERDA,"\n Olá Pedro, tudo bem?\n\n Segue abaixo..."
18,pedrogsd,PEDRO GOMES DE SÁ DRUMOND,"\n Olá Pedro, tudo bem?\n\n Segue abaixo..."
19,brunalm2,BRUNA LIMA MEINBERG,"\n Olá Bruna, tudo bem?\n\n Segue abaixo..."
20,pedrohrc1,PEDRO HENRIQUE RIZO COLPAS,"\n Olá Pedro, tudo bem?\n\n Segue abaixo..."
21,gustavoms7,GUSTAVO MENDES DA SILVA,"\n Olá Gustavo, tudo bem?\n\n Segue abai..."
22,gabrielakk,GABRIELA KATSURAYAMA,"\n Olá Gabriela, tudo bem?\n\n Segue aba..."
23,nicolasey,NICOLAS ENZO YASSUDA,"\n Olá Nicolas, tudo bem?\n\n Segue abai..."
24,pedroial,PEDRO IVO AMARAL LIMA,"\n Olá Pedro, tudo bem?\n\n Segue abaixo..."
25,lucasno,LUCAS NOVAIS DE OLIVEIRA,"\n Olá Lucas, tudo bem?\n\n Segue abaixo..."
26,pedrobp1,PEDRO BALBO PORTELLA,"\n Olá Pedro, tudo bem?\n\n Segue abaixo..."
27,isabellasa,ISABELLA DOS SANTOS DE AMORIM,"\n Olá Isabella, tudo bem?\n\n Segue aba..."
28,diogopl1,DIOGO PEREIRA LOBO,"\n Olá Diogo, tudo bem?\n\n Segue abaixo..."
29,talesitf,TALES IVALQUE TAVEIRA DE FREITAS,"\n Olá Tales, tudo bem?\n\n Segue abaixo..."
30,juliaf1,JULIA FIGUEIREDO,"\n Olá Julia, tudo bem?\n\n Segue abaixo..."
31,lucash,LUCAS HIX,"\n Olá Lucas, tudo bem?\n\n Segue abaixo..."

In [19]:
feed.shape

(32, 3)

In [20]:
feed['feedback']

0     \n    Olá Gustavo, tudo bem?\n\n    Segue abai...
1     \n    Olá Rodrigo, tudo bem?\n\n    Segue abai...
2     \n    Olá Matheus, tudo bem?\n\n    Segue abai...
3     \n    Olá Luca, tudo bem?\n\n    Segue abaixo ...
4     \n    Olá João, tudo bem?\n\n    Segue abaixo ...
5     \n    Olá Alberto, tudo bem?\n\n    Segue abai...
6     \n    Olá Douglas, tudo bem?\n\n    Segue abai...
7     \n    Olá Bruno, tudo bem?\n\n    Segue abaixo...
8     \n    Olá Gabriel, tudo bem?\n\n    Segue abai...
9     \n    Olá Alexandre, tudo bem?\n\n    Segue ab...
10    \n    Olá Kevin, tudo bem?\n\n    Segue abaixo...
11    \n    Olá Pedro, tudo bem?\n\n    Segue abaixo...
12    \n    Olá Caio, tudo bem?\n\n    Segue abaixo ...
13    \n    Olá Arthur, tudo bem?\n\n    Segue abaix...
14    \n    Olá Luana, tudo bem?\n\n    Segue abaixo...
15    \n    Olá Rafael, tudo bem?\n\n    Segue abaix...
16    \n    Olá João, tudo bem?\n\n    Segue abaixo ...
17    \n    Olá Pedro, tudo bem?\n\n    Segue abaixo...
18    \n    Olá Pedro, tudo bem?\n\n    Segue abaixo...
19    \n    Olá Bruna, tudo bem?\n\n    Segue abaixo...
20    \n    Olá Pedro, tudo bem?\n\n    Segue abaixo...
21    \n    Olá Gustavo, tudo bem?\n\n    Segue abai...
22    \n    Olá Gabriela, tudo bem?\n\n    Segue aba...
23    \n    Olá Nicolas, tudo bem?\n\n    Segue abai...
24    \n    Olá Pedro, tudo bem?\n\n    Segue abaixo...
25    \n    Olá Lucas, tudo bem?\n\n    Segue abaixo...
26    \n    Olá Pedro, tudo bem?\n\n    Segue abaixo...
27    \n    Olá Isabella, tudo bem?\n\n    Segue aba...
28    \n    Olá Diogo, tudo bem?\n\n    Segue abaixo...
29    \n    Olá Tales, tudo bem?\n\n    Segue abaixo...
30    \n    Olá Julia, tudo bem?\n\n    Segue abaixo...
31    \n    Olá Lucas, tudo bem?\n\n    Segue abaixo...
Name: feedback, dtype: object