In [1]:
import pandas as pd

In [ ]:
!ls

In [2]:
df = pd.read_excel('Copy of Avaliação Individual dos Membros (Responses).xlsx')

In [3]:
df.head(2)

,Timestamp,Email Address,Selecione o seu Nome,"Qual nível de PRODUTIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [ALBERTO MARTINS PEREIRA CARRERA]","Qual nível de PRODUTIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [DOUGLAS PABLO]","Qual nível de PRODUTIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [PEDRO GOMES DE SÁ DRUMOND]","Qual nível de PRODUTIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [PEDRO IVO AMARAL LIMA]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [ALBERTO MARTINS PEREIRA CARRERA]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [DOUGLAS PABLO]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [PEDRO GOMES DE SÁ DRUMOND]",...,"Qual nível de PRODUTIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [RAFAEL PASCARELLI NICCHERI]","Qual nível de PRODUTIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [TALES IVALQUE TAVEIRA DE FREITAS]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [LUCAS HIX]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [PEDRO BALBO PORTELLA]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [RAFAEL PASCARELLI NICCHERI]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [TALES IVALQUE TAVEIRA DE FREITAS]","Qual nível de TRANSPARÊNCIA cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [LUCAS HIX]","Qual nível de TRANSPARÊNCIA cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [PEDRO BALBO PORTELLA]","Qual nível de TRANSPARÊNCIA cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [RAFAEL PASCARELLI NICCHERI]","Qual nível de TRANSPARÊNCIA cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [TALES IVALQUE TAVEIRA DE FREITAS]"
0,2023-05-23 14:31:57.088,guoliveira255@gmail.com,Gustavo Eliziario Stevenson de Oliveira,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2023-05-23 14:35:35.035,rodrigomedeiros2002@gmail.com,RODRIGO PAOLIELLO DE MEDEIROS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.set_index('Selecione o seu Nome', inplace=True)
df.drop(['Timestamp'], axis=1, inplace=True)
df.drop(['Email Address'], axis=1, inplace=True)

In [5]:
columns = df.columns

In [6]:
df.head()

,"Qual nível de PRODUTIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [ALBERTO MARTINS PEREIRA CARRERA]","Qual nível de PRODUTIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [DOUGLAS PABLO]","Qual nível de PRODUTIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [PEDRO GOMES DE SÁ DRUMOND]","Qual nível de PRODUTIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [PEDRO IVO AMARAL LIMA]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [ALBERTO MARTINS PEREIRA CARRERA]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [DOUGLAS PABLO]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [PEDRO GOMES DE SÁ DRUMOND]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [PEDRO IVO AMARAL LIMA]","Qual nível de TRANSPARÊNCIA cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [ALBERTO MARTINS PEREIRA CARRERA]","Qual nível de TRANSPARÊNCIA cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [DOUGLAS PABLO]",...,"Qual nível de PRODUTIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [RAFAEL PASCARELLI NICCHERI]","Qual nível de PRODUTIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [TALES IVALQUE TAVEIRA DE FREITAS]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [LUCAS HIX]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [PEDRO BALBO PORTELLA]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [RAFAEL PASCARELLI NICCHERI]","Qual nível de PROATIVIDADE cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [TALES IVALQUE TAVEIRA DE FREITAS]","Qual nível de TRANSPARÊNCIA cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [LUCAS HIX]","Qual nível de TRANSPARÊNCIA cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [PEDRO BALBO PORTELLA]","Qual nível de TRANSPARÊNCIA cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [RAFAEL PASCARELLI NICCHERI]","Qual nível de TRANSPARÊNCIA cada membro teve na sprint anterior? (LEIA A RUBRICA, POIS ISSO NÃO É SIMPLESMENTE UMA NOTA)\n\nNa linha com o seu nome, faça a sua autoavaliação [TALES IVALQUE TAVEIRA DE FREITAS]"
Selecione o seu Nome,,,,,,,,,,,,,,,,,,,,,
Gustavo Eliziario Stevenson de Oliveira,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
RODRIGO PAOLIELLO DE MEDEIROS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MATHEUS RAFFAELLE NERY CASTELLUCCI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LUCA MIZRAHI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
JOÃO PEDRO RODRIGUES SANTOS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
new_columns = {}
for column in columns:
    # posição das palavras 'PRODUTIVIDADE', 'PROATIVIDADE', 'TRANSPARÊNCIA' no nome da coluna
    categoria = column.split()[3]
    nome = column.split('[')[-1].replace(']','')
    #removendo texto desnecessário da coluna e renomeando no padrão ex: PRODUTIVIDADE - NOME DO ALUN@
    new_columns[column] = f'{categoria} - {nome}'

In [8]:
df.rename(columns=new_columns, inplace=True)

In [9]:
alunos = list(df.index)
#Dicionário para armazenar as médias para criar um novo dataframe
data = {
    'nome':[],
    'media_produtividade':[],
    'media_proatividade':[],
    'media_transparência':[],
    'auto_produtividade':[],
    'auto_proatividade':[],
    'auto_transparência':[],
    'media':[]
}

In [10]:
categorias = ['PRODUTIVIDADE', 'PROATIVIDADE', 'TRANSPARÊNCIA']
for aluno in alunos:
    data['nome'].append(aluno)
    soma = 0
    for categoria in categorias:
        nome_coluna = f'{categoria} - {aluno}'
        media_colegas = df.loc[(df.index != aluno) ,nome_coluna].dropna().mean()
        soma += media_colegas
        
        auto_avaliacao = df.loc[(df.index == aluno) ,nome_coluna][0]
        
        data[f'media_{categoria.lower()}'].append(media_colegas)
        data[f'auto_{categoria.lower()}'].append(auto_avaliacao)
    data['media'].append(soma/3)

In [11]:
# data

In [12]:
df_medias = pd.DataFrame(data=data)

In [13]:
df_medias['dif_produtividade'] = df_medias['media_produtividade'] - df_medias['auto_produtividade']
df_medias['dif_proatividade'] = df_medias['media_proatividade'] - df_medias['auto_proatividade']
df_medias['dif_transparência'] = df_medias['media_transparência'] - df_medias['auto_transparência']

In [14]:
df_medias.loc[:,['nome','dif_produtividade','dif_proatividade','dif_transparência']]

,nome,dif_produtividade,dif_proatividade,dif_transparência
0,Gustavo Eliziario Stevenson de Oliveira,0.500000,0.500000,0.500000
1,RODRIGO PAOLIELLO DE MEDEIROS,0.000000,0.000000,0.000000
2,MATHEUS RAFFAELLE NERY CASTELLUCCI,0.000000,0.000000,0.000000
3,LUCA MIZRAHI,0.500000,0.500000,0.500000
4,JOÃO PEDRO RODRIGUES SANTOS,0.000000,0.000000,0.000000
5,ALBERTO MARTINS PEREIRA CARRERA,0.000000,0.000000,0.000000
6,DOUGLAS PABLO,0.000000,0.000000,0.000000
7,BRUNO MARQUES LI VOLSI FALCAO,0.000000,-1.000000,-1.000000
8,GABRIEL MENDONÇA DE MELLO HERMIDA,0.000000,0.000000,0.000000
9,ALEXANDRE RODRIGUES SANTAROSSA,0.000000,0.000000,0.000000
10,KEVIN NAGAYUKI SHINOHARA,0.666667,0.666667,0.666667
11,PEDRO TOLEDO PIZA CIVITA,0.000000,0.000000,0.000000
12,CAIO ORTEGA BÔA,0.000000,0.000000,0.000000
13,ARTHUR MOREIRA TAMM,0.000000,0.000000,0.000000
14,LUANA WILNER ABRAMOFF,0.000000,0.000000,0.000000
15,RAFAEL PASCARELLI NICCHERI,0.000000,0.000000,0.000000
16,JOÃO ANTÔNIO GOMES GARCIA,0.000000,0.000000,0.000000
17,PEDRO AUGUSTO GEVE DE MORAES LACERDA,0.000000,0.000000,0.000000
18,PEDRO GOMES DE SÁ DRUMOND,0.000000,0.000000,0.000000
19,BRUNA LIMA MEINBERG,0.000000,0.000000,0.000000
20,PEDRO HENRIQUE RIZO COLPAS,0.000000,0.000000,0.000000
21,GUSTAVO MENDES DA SILVA,0.666667,0.666667,0.666667
22,GABRIELA KATSURAYAMA,-0.666667,-0.666667,-0.666667
23,NICOLAS ENZO YASSUDA,-0.666667,-0.666667,-0.666667
24,PEDRO IVO AMARAL LIMA,0.000000,0.000000,0.000000
25,LUCAS NOVAIS DE OLIVEIRA,0.000000,0.000000,0.000000
26,PEDRO BALBO PORTELLA,0.000000,0.000000,0.000000
27,ISABELLA DOS SANTOS DE AMORIM,0.000000,0.000000,0.000000
28,DIOGO PEREIRA LOBO,0.000000,0.000000,0.000000
29,TALES IVALQUE TAVEIRA DE FREITAS,0.000000,0.000000,0.000000
30,JULIA FIGUEIREDO,0.000000,0.000000,0.000000
31,LUCAS HIX,0.000000,0.000000,0.000000

# Verificando respostas duplicadas

In [15]:
#fazer algo para identificar alunos que responderam o formulário mais de uma vez e pegar a última resposta
#verificar pessoas que não responderam

In [16]:
df_count = df_medias.groupby(['nome'])['nome'].count().to_frame('count')
df_count.loc[df_count["count"]>1,:]

Empty DataFrame
Columns: [count]
Index: []

# Salvando em arquivo

In [17]:
df_medias.to_excel('sprint2_medias.xlsx')

In [18]:
df_medias.shape

(32, 11)

In [19]:
df.shape

(32, 102)